project:
  type: website
  output-dir: _site

execute:
    error: true
    echo: true
    enabled: true
    daemon: 300
    freeze: auto

julia:
    exeflags: ["--project=@.", "--threads=1"]

website:
  title: "2026 PINNs Workshop"
  navbar:
    logo: images/aims-logo.svg
    logo-alt: "AIMS"
    logo-href: /index.html
    title-href: /index.html
  sidebar:
    style: floating
    search: true
    contents:
      - text: Course Overview
        href: index.qmd
      - section: Curriculum
        contents:
          - units/unit_01/unit_01.qmd
          - units/unit_02/unit_02.qmd
          - units/unit_03/unit_03.qmd
          - units/unit_04/unit_04.qmd
          - units/unit_05/unit_05.qmd
          - units/unit_06/unit_06.qmd
          - units/unit_07/unit_07.qmd
          - units/unit_08/unit_08.qmd
          - units/unit_09/unit_09.qmd
          - units/unit_10/unit_10.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    html-math-method: katex
    anchor-sections: true
    smooth-scroll: true
    respect-user-color-scheme: true
    page-navigation: true
    toc: true
    toc-depth: 2
    toc-expand: 2
    toc-title: Contents
    number-sections: true
    number-depth: 1
    code-copy: true
    fig-format: svg
    fig-width: 8
    fig-height: 6
    highlight-style: github
    include-after-body: toc-date.html
    embed-resources: true
    link-external-newwindow: true
