{
  "hash": "ab7e89f02438e05317a58c104d495aad",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"Unit 2: ML Foundations: From Classical to Deep\"\nengine: julia\ntoc-title: \"Unit 2: ML Foundations\"\ndate: today\ndate-format: \"DD/MM/YYYY\"\n---\n\nA walk from supervised learning and random forests through to neural\nnetworks, optimisation, and the autodiff stack that PINNs sit on.\nThis unit follows the framing of *Mathematical Engineering of Deep\nLearning* (Liquet, Moka & Nazarathy), chapters 2–6, with code in Julia\n(`DecisionTree.jl` for classical ML, `Lux.jl` for deep networks) and a\n`scikit-learn` / `PyTorch` comparison so the cross-ecosystem story\nstays in view.\n\nA single unit can't cover everything — the goal here is *shared\nvocabulary* and a feel for which classical ideas survive the journey\nto PINNs.\n\n## 2.1 Supervised learning fundamentals\n\n### The setup\n\nGiven labelled data $\\{(x_i, y_i)\\}_{i=1}^N$, learn a function\n$f: \\mathbb{R}^n \\to \\mathcal{Y}$ such that $f(x) \\approx y$ on\nunseen inputs. The output space $\\mathcal{Y}$ is continuous\n(regression) or a finite set (classification). The art of supervised\nlearning is choosing a **function class** — linear, tree-based,\nneural — and a **fitting procedure** that *generalises* beyond the\ntraining set.\n\n### Loss, true risk, empirical risk\n\nA **loss** $\\ell(\\hat y, y)$ measures how bad a single prediction\nis. The **true risk** is the population mean\n\n$$R(f) = \\mathbb{E}_{(x, y)}[\\ell(f(x), y)].$$\n\nWe can't compute it, so we minimise the **empirical risk**\n\n$$\\hat R(f) = \\frac{1}{N}\\sum_{i=1}^N \\ell(f(x_i), y_i).$$\n\nAll of supervised learning is a story about how, when, and *whether*\n$\\hat R$ approximates $R$. PINNs are no exception — their \"data\"\nincludes scattered collocation points where the loss is a PDE\nresidual rather than a label, but the ERM picture survives intact\n([Unit 5](../unit_05/unit_05.qmd)).\n\n### Train, validate, test — and $k$-fold cross-validation\n\nThe standard split: **training** to fit, **validation** to pick\nhyperparameters, **test** to estimate true risk. Never let the test\nset influence model choice.\n\nWhen data is scarce, hold out one validation set at a time and\nrotate. That's **$k$-fold cross-validation**:\n\n![$k$-fold cross-validation. Each row trains on the unshaded blocks and validates on the shaded one; cross-validated risk averages the $k$ held-out scores. (Figure from *Mathematical Engineering of Deep Learning*, §2.5.)](figures/figure2-11-kfold_cross_validation.svg)\n\n### Bias, variance, and model complexity\n\nHolding $N$ fixed and sweeping the function class from simple to\ncomplex, training error decreases monotonically while test error is\n$U$-shaped: too simple under-fits (high bias), too complex over-fits\n(high variance). The minimum of the test-error curve marks the\n\"right\" complexity for that dataset size.\n\n![Test (red) and training (green) error vs. model complexity. The classical bias–variance trade-off: complexity beyond the right-hand side of the dotted line buys lower training error at the cost of higher test error. (Figure from *MEDL*, §2.7.)](figures/figure2-9-error_modelcomplexity.svg)\n\nFor PINNs the same picture applies: the function class is set by the\nnetwork architecture, \"complexity\" is roughly the parameter count,\nand the test set is replaced by held-out collocation points in the\nPDE domain.\n\n::: {#ex-2-1 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — watch the U-shape appear\n\nMake the bias–variance trade-off concrete. Generate 60 noisy\nsamples of $y = \\sin(2\\pi x) + \\varepsilon$,\n$\\varepsilon \\sim \\mathcal{N}(0, 0.2^2)$, on $x \\in [0, 1]$. Fit\npolynomials of degree $1, 2, \\ldots, 15$ by least squares, and for\neach degree compute (a) the training RMSE and (b) the\n**5-fold cross-validated** RMSE — implementing the fold rotation\nyourself, no library. Plot both curves against degree. Where is the\nminimum of the CV curve, and what happens to the two curves past it?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\nDesign matrix: `vander(x, d) = hcat((x .^ p for p in 0:d)...)`; fit each degree with `c = vander(x, d) \\ y` and score with `rmse(a, b) = sqrt(mean(abs2, a .- b))`. For the 5 interleaved folds use `folds = [i:5:N for i in 1:5]`; per fold build a boolean `test`, refit on `vander(x[.!test], d) \\ y[.!test]`, and score on `x[test]`. Loop `for d in 1:15`, plot both RMSE curves (try `yscale = :log10`), and expect numerical warnings past degree ~12 — that ill-conditioning is part of the story.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-1)\n:::\n:::\n\n## 2.2 Random forests on MNIST: a cross-language comparison\n\nBefore deep learning takes over, one quick stop on the\nnon-deep-learning side of the world — and a first look at MNIST,\nthe dataset we'll keep using as a running example. The next few\nsubsections cover what a random forest *is*, a first look at the\ndigits, and the same MNIST problem in Julia and in Python, so the\ncross-ecosystem template is established up front.\n\n### Decision trees, ensembled\n\nA **decision tree** partitions the input space by axis-aligned\nsplits, with a constant prediction at each leaf. Greedy fitting\npicks the split that reduces a loss criterion most at each node —\nvariance for regression, Gini or entropy for classification. Trees\nare interpretable but **high-variance**: small data perturbations\nproduce wildly different trees.\n\nA **random forest** mitigates the variance by averaging many trees\ntrained on bootstrap resamples of the data, with each split\nconsidering only a random subset of features. The variance falls,\ngeneralisation goes up, interpretability becomes harder to maintain.\nRandom forests are still a serious baseline on tabular *or* flat\nimage problems — often the right tool when you have\nhundreds-of-thousands of rows of modestly sized feature vectors,\nhand-designed or otherwise.\n\n### The MNIST benchmark\n\n**MNIST** is 70 000 grayscale images of handwritten digits 0–9,\neach $28 \\times 28$ pixels (so 784 features when flattened to a\nvector). 60 000 are reserved for training, 10 000 for test. It is\nthe canonical \"easy classification benchmark\" in deep learning —\nsmall enough to fit in memory, hard enough that a naive baseline\nisn't perfect, and used in\n[*Mathematical Engineering of Deep Learning*](../references/references.qmd#ref-liquet2024){target=\"_blank\"}\n(Chapters 5–6) for exactly the kind of side-by-side comparison\nwe're about to do.\n\n### A first look at the digits\n\nBefore training anything, it's worth *looking* at the data. Each MNIST sample is\na $28 \\times 28$ grayscale image; flattened to a length-784 vector of pixel\nintensities, that raw vector is all every model in this unit — forest, softmax,\nMLP — ever sees (only the convolutional network in §2.8 keeps the 2-D grid). Load\nthe training split and show the first 40 digits with their labels:\n\n```{.julia}\nusing MLDatasets, Plots\n\n# train_x is 28×28×60000 with pixel values already in [0,1]; train_y are labels 0–9\ntrain_x, train_y = MLDatasets.MNIST(split = :train)[:]\n\npanels = map(1:40) do i\n    heatmap(transpose(train_x[:, :, i]);          # transpose + yflip ⇒ upright digit\n            yflip = true, color = :grays, aspect_ratio = 1,\n            axis = false, ticks = false, colorbar = false, legend = false,\n            title = string(train_y[i]), titlefontsize = 7)\nend\nplot(panels...; layout = (5, 8), size = (760, 500),\n     plot_title = \"MNIST — first 40 training digits\")   # in a notebook this renders inline\n```\n\n![The first 40 MNIST training digits, with their labels. Each is a $28\\times28$ grayscale image — 784 raw pixel values, which is all a *flat* classifier ever sees.](figures/mnist_digits.png)\n\n*Setup note.* `MLDatasets.jl` — the dataset loader used here and by the forest\nbelow — isn't in the workshop `Project.toml` by default (we keep the PINN deps\nminimal). Add it once with `Pkg.add(\"MLDatasets\")` from the repo root. This\nre-resolves your personal environment and precompiles MLDatasets' own dependency\nclosure — a few minutes, one-off, cached afterwards — so do it at a break, not\nmid-exercise. It installs into *your* home environment and doesn't disturb the\nshared PINN stack, so `using NeuralPDE` stays fast. Why this is a separate step:\n[The `@pinn` Julia environment](../pinn_env/pinn_env.qmd#adding-packages).\n\n### MNIST random forest in Julia (`DecisionTree.jl`)\n\nA 100-tree forest on flattened MNIST takes a couple of minutes to\nfit and lands around **97% test accuracy** — a strong baseline that\ntook deep learning a decade to convincingly beat. We call\n`DecisionTree.jl` (already in the workshop `Project.toml`) directly,\nwith `MLDatasets.jl` for the MNIST loader. For broader classical-ML\nwork, Julia's umbrella framework is\n[`MLJ.jl`](https://github.com/JuliaAI/MLJ.jl){target=\"_blank\"} — a\nunified, `scikit-learn`-style interface over dozens of models — but we\nuse `DecisionTree.jl` on its own here to keep the dependencies light:\n\n```{.julia filename=\"units/unit_02/scripts/mnist_rf_julia.jl\"}\nusing MLDatasets, DecisionTree, Statistics\n\ntrain_x, train_y = MLDatasets.MNIST(split = :train)[:]\ntest_x,  test_y  = MLDatasets.MNIST(split = :test)[:]\n\n# (28, 28, N) → (N, 784); MLDatasets already returns pixels in [0, 1]\nflatten(x) = reshape(Float32.(x), 28 * 28, size(x, 3))'\nX_train, X_test = flatten(train_x), flatten(test_x)\ny_train, y_test = Int.(train_y), Int.(test_y)\n\n# Native DecisionTree.jl API\nforest = build_forest(\n    y_train, X_train,\n    28,           # n_subfeatures (≈ √784)\n    100,          # n_trees\n    0.7,          # partial_sampling\n    -1,           # max_depth\n    1, 2, 0.0;    # min_samples_leaf, min_samples_split, min_purity_increase\n    rng = 0,\n)\nŷ = apply_forest(forest, X_test)\n@info \"MNIST test accuracy (DecisionTree.jl RF, 100 trees) = $(round(mean(ŷ .== y_test); digits = 4))\"\n```\n\n(This uses the same `MLDatasets` loader as the digit display above — see that\n*setup note* if you haven't added it yet.)\n\n### MNIST random forest in Python (`scikit-learn`)\n\nSame problem, same numbers, in the Python ecosystem:\n\n```{.python filename=\"units/unit_02/scripts/mnist_rf_sklearn.py\"}\nfrom sklearn.datasets import fetch_openml\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score\n\n# fetch_openml caches to ~/scikit_learn_data/ after the first download\nX, y = fetch_openml(\"mnist_784\", version=1, as_frame=False, return_X_y=True)\nX = X.astype(\"float32\") / 255.0\ny = y.astype(\"int64\")\n\nX_train, X_test = X[:60_000], X[60_000:]\ny_train, y_test = y[:60_000], y[60_000:]\n\nclf = RandomForestClassifier(\n    n_estimators=100, n_jobs=-1, random_state=0,\n)\nclf.fit(X_train, y_train)\nacc = accuracy_score(y_test, clf.predict(X_test))\nprint(f\"MNIST test accuracy (sklearn RF, 100 trees): {acc:.4f}\")\n```\n\nRun it yourself with\n[`scripts/mnist_rf_sklearn.py`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_02/scripts/mnist_rf_sklearn.py){target=\"_blank\"}\n(or `./build.sh execute 2` once you've installed `scikit-learn`).\nTypical first-run cost: ~30 s download (cached after) + ~2 min\nfit on a modern laptop CPU.\n\nThe point isn't the accuracy number — it's that the same problem\nin two ecosystems has the **same shape**: load data, choose a model,\nfit, score. This template recurs throughout the workshop.\n\n### When classical ML wins\n\nRandom forests (and gradient boosting, and regularised linear\nmodels) still beat neural networks when:\n\n- the dataset is **small** (hundreds to thousands of rows),\n- the features are **tabular and well-engineered**, or\n- **interpretability** matters and you can pay the per-tree\n  inspection cost.\n\nDeep learning's edge sharpens with high-dimensional unstructured\ninputs (images, text, audio), large datasets, and — as we'll see in\n[Unit 5](../unit_05/unit_05.qmd) onwards — *PDE residuals*.\n\n::: {#ex-2-2 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — how many trees is enough?\n\nTake the `DecisionTree.jl` MNIST script above and sweep the forest\nsize: $n_{\\text{trees}} \\in \\{1, 5, 20, 50, 100, 200\\}$ (use a\n10 000-image training subset to keep each fit under ~20 s). Plot\ntest accuracy against tree count. Then hold 100 trees fixed and\nsweep `n_subfeatures` over $\\{5, 28, 100, 784\\}$. Two questions:\nwhere does the accuracy curve flatten, and why does\n`n_subfeatures = 784` (every split sees every feature) *hurt* the\nensemble even though each individual tree gets stronger?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\nReuse the section's `build_forest` call — argument 3 is `n_subfeatures`, argument 4 is `n_trees`; vary just those in a loop. MLDatasets already returns pixels in [0,1], so you can drop the `/255` and flatten with `reshape(Float32.(x), 784, :)'`. Subset `X[1:10_000, :]` (and matching labels) to keep each fit fast; the *shape* of the curves is robust to the subset. Score with `mean(apply_forest(forest, Xt) .== yt)`. For the 784 case: when every split sees every feature, all trees pick the same dominant splits and their errors stop being decorrelated — and averaging correlated errors removes less noise.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-2)\n:::\n:::\n\n## 2.3 From logistic regression to a neural network\n\nThe simplest possible \"neural network\" is a single linear layer\nfollowed by a smooth squashing function. It is also the first\ngenuinely useful classifier — the **softmax regression** baseline\nthat [*Mathematical Engineering of Deep Learning*](../references/references.qmd#ref-liquet2024){target=\"_blank\"}\nderives in detail in Chapter 3 (*Simple Neural Networks*). The next four subsections\nwalk through the theory (Bernoulli → sigmoid → softmax) and then\nfit it on MNIST in both Julia and Python, so the jump to deeper\nnetworks in §2.4 is a single conceptual step rather than a leap.\n\n### Bernoulli likelihood and the sigmoid\n\nFor binary classification, model\n$P(y = 1 \\mid x) = \\sigma(w^\\top x + b)$ with the sigmoid\n$\\sigma(z) = 1/(1 + e^{-z})$. Maximising the Bernoulli likelihood\nover training data is equivalent to minimising the **binary\ncross-entropy**\n\n$$\\mathcal{L}(w, b) =\n-\\tfrac{1}{N}\\sum_i \\bigl[y_i \\log \\hat p_i + (1-y_i) \\log (1-\\hat p_i)\\bigr],$$\n\nwhere $\\hat p_i = \\sigma(w^\\top x_i + b)$. That single-layer\n$x \\mapsto \\sigma(w^\\top x + b)$ is the simplest neural network — a\nlinear map followed by a smooth nonlinearity.\n\n### Softmax for multiclass\n\nStack the binary case $K$ times and renormalise with the\n**softmax**\n\n$$\\mathrm{softmax}(z)_k = \\frac{e^{z_k}}{\\sum_{j=1}^K e^{z_j}}.$$\n\nThe model becomes $P(y = k \\mid x) = \\mathrm{softmax}(Wx + b)_k$,\nfit by **categorical cross-entropy**.\n\n![A logistic / softmax classifier as a one-layer neural network. The affine map $Wx + b$ feeds a softmax that outputs class probabilities. (Figure from *MEDL*, §3.3.)](figures/figure3-3-logistic_architecture.svg)\n\n### MNIST softmax regression in `Lux.jl`\n\nThe \"deep learning baseline\" — a single linear layer + softmax,\ntrained by maximum likelihood — on the same MNIST data the forest\njust saw. With no nonlinearity and no hidden units, this is\nliterally the simple network *MEDL* introduces in\n[Chapter 3](../references/references.qmd#ref-liquet2024){target=\"_blank\"} before\nmotivating the deeper feedforward networks of Chapter 5. Expect **~92% test accuracy** — a\nstriking gap below the random forest's ~97%, which is the point.\n\n```{.julia filename=\"units/unit_02/scripts/mnist_linear_lux.jl\"}\nusing MLDatasets, Lux, Random, Zygote, Optimisers, Statistics\n\n# data ─────────────────────────────────────────────────────────────────\ntrain_x, train_y = MLDatasets.MNIST(split = :train)[:]\ntest_x,  test_y  = MLDatasets.MNIST(split = :test)[:]\nflatten(x) = reshape(Float32.(x), 28 * 28, size(x, 3))\nX_train, X_test = flatten(train_x), flatten(test_x)\ny_train, y_test = Int.(train_y), Int.(test_y)\n\nonehot(k, K = 10) = (e = zeros(Float32, K); e[k + 1] = 1f0; e)\nY_train = reduce(hcat, onehot.(y_train))\n\n# model: 784 → 10 (single linear layer + softmax) ─────────────────────\nrng = Random.MersenneTwister(0)\nmodel = Lux.Chain(Lux.Dense(784 => 10), Lux.softmax)\nps, st = Lux.setup(rng, model)\n\n# cross-entropy loss ───────────────────────────────────────────────────\nfunction loss_fn(ps, st, X, Y)\n    ŷ, st = model(X, ps, st)\n    -mean(sum(Y .* log.(ŷ .+ 1f-9); dims = 1)), st\nend\n\n# mini-batch SGD (Adam) ────────────────────────────────────────────────\nopt_state = Optimisers.setup(Optimisers.Adam(1f-2), ps)\nbatch     = 128\nnb        = size(X_train, 2) ÷ batch\nfor epoch in 1:10\n    perm = randperm(rng, size(X_train, 2))\n    for b in 1:nb\n        idx = perm[(b - 1) * batch + 1 : b * batch]\n        gs  = first(Zygote.gradient(\n                p -> first(loss_fn(p, st, X_train[:, idx], Y_train[:, idx])),\n                ps,\n              ))\n        opt_state, ps = Optimisers.update(opt_state, ps, gs)\n    end\nend\n\nŷ_test, _ = model(X_test, ps, st)\npreds = vec(map(argmax, eachcol(ŷ_test))) .- 1\n@info \"MNIST test accuracy (Lux softmax) = $(round(mean(preds .== y_test); digits = 4))\"\n```\n\nThis is the *same* skeleton you'll see again in every PINN: define\nthe model as a pure function, separate parameters `ps` from\ninference state `st`, build a loss, take gradients with\n`Zygote.gradient`, step with `Optimisers.update`. The only thing\nPINNs add is more loss terms.\n\nThe Lux style — parameters as plain arrays, not hidden state —\nmatters because `NeuralPDE.jl` ([Unit 5](../unit_05/unit_05.qmd))\nneeds to *compose* layers with PDE-residual losses that contain\nderivatives of the network output. Frameworks like `scikit-learn`\nthat hide their parameters can't do that composition.\n\n### MNIST softmax regression in Python (`scikit-learn`)\n\nSame model, fewer lines, very similar numbers:\n\n```{.python filename=\"units/unit_02/scripts/mnist_linear_sklearn.py\"}\nfrom sklearn.datasets import fetch_openml\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import accuracy_score\n\nX, y = fetch_openml(\"mnist_784\", version=1, as_frame=False, return_X_y=True)\nX = X.astype(\"float32\") / 255.0\ny = y.astype(\"int64\")\n\nX_train, X_test = X[:60_000], X[60_000:]\ny_train, y_test = y[:60_000], y[60_000:]\n\n# Multinomial logistic = softmax regression\nclf = LogisticRegression(\n    solver=\"lbfgs\", max_iter=200, n_jobs=-1, random_state=0,\n)\nclf.fit(X_train, y_train)\nacc = accuracy_score(y_test, clf.predict(X_test))\nprint(f\"MNIST test accuracy (softmax regression): {acc:.4f}\")\n```\n\nAvailable as\n[`scripts/mnist_linear_sklearn.py`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_02/scripts/mnist_linear_sklearn.py){target=\"_blank\"}.\nRuntime: ~30 s on a laptop CPU. Notice that `scikit-learn` itself\nuses **L-BFGS** internally for this convex problem — the same\noptimiser we'll use for the fine-tuning stage of every PINN in\n[Units 5–7](../unit_05/unit_05.qmd). Convex losses are why L-BFGS\nconverges so cleanly here; in deeper networks the loss surface\nisn't convex and we'll need Adam.\n\n::: {#ex-2-3 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — logistic regression from scratch\n\nStrip the framework away entirely. Using only plain Julia arrays\n(no `Lux`, no `Zygote`), implement binary logistic regression for\nthe digits **0 vs 1** of MNIST: write the sigmoid, the binary\ncross-entropy, derive the gradient\n$\\nabla_w \\mathcal{L} = \\frac{1}{N} X (\\hat p - y)$ by hand, and run\n500 steps of plain gradient descent. You should clear 99% test\naccuracy on this easy pair. Then swap in the digits **4 vs 9** and\nwatch the same model struggle — why is that pair so much harder for\na *linear* decision boundary?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\nNo autodiff needed: for sigmoid + binary cross-entropy the per-example gradient collapses to `p̂ .- y` (the $\\sigma'$ cancels against the log), so with `X` kept as 784×N (columns are images) the update is `w -= η .* (X * δ) ./ N` and `b -= η .* mean(δ)`, where `δ = σ(X'w .+ b) .- y`. Select the pair with a mask `(y .== 0) .| (y .== 1)` and set the label `Float32.(y .== 1)`. Use `η = 0.5`, 500 steps — about twenty lines. Then swap in 4-vs-9: the discriminator (does the upper loop close?) is a conjunction of pixels no single linear threshold can express.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-3)\n:::\n:::\n\n## 2.4 Feedforward networks\n\n### MLPs: depth $\\times$ width\n\nA **multilayer perceptron (MLP)** stacks affine layers with\nelementwise nonlinearities $\\sigma$ in between:\n\n$$f_\\theta(x) = W_L\\,\\sigma\\!\\bigl(W_{L-1}\\,\\sigma(\\cdots W_1 x + b_1 \\cdots) + b_{L-1}\\bigr) + b_L.$$\n\nA one-hidden-layer network is enough to demonstrate the architecture\nshape:\n\n![One hidden layer. The input vector flows through an affine map + nonlinearity to a hidden representation, then a final linear projection. (Figure from *MEDL*, §5.1.)](figures/figure5-1-a-one_hidden_layer.svg)\n\nDepth lets the network compose features; width gives it room to\nrepresent each:\n\n![A deeper feedforward network — same picture, repeated. (Figure from *MEDL*, §5.1.)](figures/figure5-1-b-deep_neural_network.svg)\n\n### Universal approximation\n\nA two-layer MLP with a non-polynomial activation can approximate any\ncontinuous function on a compact set to arbitrary accuracy, given\nenough hidden units ([Hornik, 1991](../references/references.qmd#ref-hornik1991){target=\"_blank\"}; [Cybenko, 1989](../references/references.qmd#ref-cybenko1989){target=\"_blank\"}). The theorem is\n**qualitative**: it doesn't tell you how many units, how much data,\nor how to train. Depth, architectural priors, and good optimisation\nmake the practical difference.\n\n### Activation choices (with a PINN aside)\n\nCommon nonlinearities — the two smooth ones first, since they matter most\nfor PINNs:\n\n- **Sigmoid** $\\sigma(z) = \\dfrac{1}{1 + e^{-z}}$ — squashes the whole real\n  line into $(0, 1)$; the classic \"soft switch.\"\n- **tanh** $\\tanh(z) = \\dfrac{e^{z} - e^{-z}}{e^{z} + e^{-z}} = 2\\,\\sigma(2z) - 1$\n  — the same S-shape, rescaled to $(-1, 1)$ and centred at zero. Sigmoid\n  and tanh are smooth and bounded, so they **saturate**: deep networks built\n  from them tend to gradient-vanish.\n- **ReLU** $\\max(0, z)$ — cheap, non-saturating, the modern default for\n  vision and language tasks.\n- **Swish** $z\\,\\sigma(\\beta z)$ — a smoothed ReLU; a good default for PINNs.\n\n![The four activations on $[-5, 5]$: sigmoid and tanh are the smooth, bounded S-curves; ReLU is the piecewise-linear default; Swish is a smoothed ReLU. (Generated by `scripts/activations.jl`.)](figures/activations.png)\n\n**Why the smooth ones are central for PINNs.** A PINN's loss contains\n*derivatives* of the network's output — often the second derivative, which\nshows up in the PDE residual (the autodiff machinery later in this unit,\nleaned on hard from [Unit 5](../unit_05/unit_05.qmd) on). ReLU's second\nderivative is zero almost everywhere, so a ReLU network cannot even form a\ndiffusion-type residual like $u_{xx}$. Smooth activations keep every\nderivative alive — which is why PINNs use them: the workshop defaults to\n**Swish** from [Unit 5](../unit_05/unit_05.qmd) on, with **tanh** the other\nstandard choice. Sigmoid and tanh are the two to keep at your fingertips —\nevery smooth activation is a variation on that same S-curve.\n\n::: {#ex-2-4 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — universal approximation, and the ReLU trap\n\nFit a one-hidden-layer `Lux` MLP to\n$f(x) = \\sin(4\\pi x) \\cdot e^{-x}$ on $[0, 1]$ at widths\n$5, 20, 100$, and plot the three fits over the target. Then — the\nPINN-relevant part — take the width-20 network in two versions,\n`tanh` and `relu`, and use nested `ForwardDiff.derivative` to plot\nthe *second* derivative $f_\\theta''(x)$ of each. The `tanh` network\ngives a smooth curve; what does the ReLU network give, and why does\nthat disqualify it from any diffusion-type PDE residual?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\nBuild each net as `Lux.Chain(Lux.Dense(1 => w, act), Lux.Dense(w => 1))` with `act = tanh` or `relu`, and train it with the same `Zygote.gradient` + `Optimisers.Adam(1f-2)` loop used in §2.3. For the second derivative, reuse the nested-`ForwardDiff.derivative` pattern from §2.7: wrap the trained net in a scalar closure `u(x) = first(model([x], ps, st))[1]`, then `f2(x) = ForwardDiff.derivative(ξ -> ForwardDiff.derivative(u, ξ), x)`. The tanh `f2` is smooth; the ReLU one is identically zero (a piecewise-linear net), so a `u_xx` residual built on ReLU silently solves the wrong equation.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-4)\n:::\n:::\n\n## 2.5 On using Lux.jl {#sec-lux}\n\nEvery neural network in this workshop — and every PINN from\n[Unit 5](../unit_05/unit_05.qmd) on — is built with\n[`Lux.jl`](https://lux.csail.mit.edu){target=\"_blank\"}. The previous\nsections already used it in passing; this section is a short, standalone\ntour of the handful of functions you actually need, with the\n[Lux documentation](https://lux.csail.mit.edu){target=\"_blank\"} worth\nkeeping open alongside.\n\n### The core idea: parameters live outside the model\n\nA `Lux` model is an **immutable description** of an architecture — it holds\n*no* weights. The parameters (`ps`) and any auxiliary state (`st`, e.g. a\n`BatchNorm` running average) live in **separate** objects you create once and\nthen thread through every call by hand:\n\n```{.julia}\nusing Lux, Random\n\nmodel = Lux.Chain(\n    Lux.Dense(784 => 128, tanh),   # affine 784→128, then tanh\n    Lux.Dense(128 => 10),          # affine 128→10 (logits)\n)\n\nrng    = Random.MersenneTwister(0)\nps, st = Lux.setup(rng, model)     # ps = parameters, st = state\n```\n\n`Lux.setup` initialises the parameters (Glorot by default) and returns the\npair. From here on `model`, `ps`, and `st` are three separate things you\ncarry together. This is the single most important Lux convention, and the\nreason the SciML / PINN stack is built on it: a loss can be differentiated\ncleanly with respect to `ps` because `ps` is just a `NamedTuple` of arrays,\nnot hidden inside the model.\n\n### Specifying a network\n\nThe two main building blocks:\n\n- **`Lux.Dense(in => out, activation)`** — a fully-connected layer\n  $x \\mapsto \\sigma(Wx + b)$. Omit the activation for a plain affine map.\n- **`Lux.Chain(layer1, layer2, …)`** — compose layers front to back.\n\nThat covers every MLP in this unit. Other layers slot in the same way —\n`Lux.Conv`, `Lux.MaxPool` (the LeNet CNN of §2.8), `Lux.BatchNorm`,\n`Lux.Dropout`, or `Lux.WrappedFunction(f)` to drop an arbitrary function into\na chain.\n\n### Inference: calling the model\n\nA `Lux` model is called as a **pure function** `model(x, ps, st)` and returns\na tuple `(output, new_state)`:\n\n```{.julia}\nx = randn(Float32, 784, 32)         # a batch of 32 inputs (columns)\nŷ, st = model(x, ps, st)            # ŷ is 10×32; st unchanged here (Dense is stateless)\n```\n\nInputs are **column-major**: features down the rows, batch across the\ncolumns, so a `784 => 128` layer expects a `784 × batch` matrix. For layers\nwhose behaviour differs between training and inference (`Dropout`,\n`BatchNorm`) switch to evaluation behaviour with `Lux.testmode(st)` before\npredicting.\n\n### Activations and one-hot encoding\n\nActivations are ordinary functions — pass them by name to a layer. Lux\nre-exports the common ones from\n[`NNlib.jl`](https://github.com/FluxML/NNlib.jl){target=\"_blank\"}: `relu`,\n`tanh`, `sigmoid`, `swish`, `gelu`, `softplus`, … plus `softmax` for the\noutput. This is exactly the §2.4 menu; for PINNs the default is `tanh` or\n`swish`.\n\n```{.julia}\nLux.Dense(128 => 10, relu)          # ReLU layer\nLux.Dense(128 => 10, swish)         # Swish — the PINN default\n```\n\nFor classification you want integer labels as **one-hot columns**.\nHand-rolling it is a one-liner (as in §2.3), but the ecosystem helper is\n`onehotbatch` from\n[`OneHotArrays.jl`](https://github.com/FluxML/OneHotArrays.jl){target=\"_blank\"}:\n\n```{.julia}\nusing OneHotArrays\nY     = onehotbatch(y_train, 0:9)   # 10 × N one-hot matrix\npreds = onecold(ŷ, 0:9)             # argmax back to labels 0–9\n```\n\n### Training: the standard loop\n\nTraining is the §2.3 skeleton — and it is the *same* skeleton every PINN\nuses. Take gradients of a scalar loss with respect to `ps` (reverse-mode AD,\n§2.7), then step an optimiser:\n\n```{.julia}\nusing Zygote, Optimisers\n\nfunction loss_fn(ps)\n    ŷ, _ = model(X, ps, st)\n    mean(abs2, ŷ .- Y)              # any scalar loss\nend\n\nopt_state = Optimisers.setup(Optimisers.Adam(1f-2), ps)   # Adam: see §2.6\nfor step in 1:1000\n    g = first(Zygote.gradient(loss_fn, ps))               # ∂loss/∂ps, a NamedTuple\n    opt_state, ps = Optimisers.update(opt_state, ps, g)   # functional update\nend\n```\n\nTwo things to notice. `Optimisers.update` **returns** a new\n`(opt_state, ps)` rather than mutating in place — you rebind them each step.\nAnd the optimiser itself (`Adam`, `Descent`, and the L-BFGS that finishes\nevery PINN) is the subject of §2.6; here just treat `Adam(1f-2)` as a\nsensible default.\n\n### Inspecting a trained model\n\n`ps` is a plain `NamedTuple`, so the trained weights are right there to read:\n\n```{.julia}\nLux.parameterlength(model)    # total trainable parameter count\nLux.statelength(model)        # size of the state st\nps.layer_1.weight             # the 128×784 weight matrix of the first Dense\nps.layer_1.bias               # its bias vector\n```\n\n`Lux.parameterlength` is what §2.8's exercise uses to compare model sizes;\nand because `ps` is just nested arrays you can save it, move it to the GPU\n(`ps |> gpu_device()`, §2.8), or hand it to `NeuralPDE.jl` unchanged.\n\n### Why this design — Lux vs Flux, and the other frameworks\n\nJulia's older deep-learning library,\n[`Flux.jl`](https://fluxml.ai){target=\"_blank\"}, stores parameters *inside*\nthe layer objects (a `Dense` carries its own `W` and `b`), so a model is a\nmutable, stateful thing. `Lux.jl` deliberately splits them apart: the model\nis an immutable, **explicit-parameter** function `f(x, ps, st)`. That\nfunctional style is what makes Lux the right substrate for SciML and PINNs —\nwhen the loss contains derivatives of the network itself (§2.7), the autodiff\nand the PDE machinery need the parameters as an explicit, immutable argument\nthey can differentiate and reshape, not as hidden state. It also keeps GPU\nmovement and reproducibility (`rng` in, `ps` out) clean.\n\nFor orientation across ecosystems:\n\n- **PyTorch** — like Flux: parameters live on the `nn.Module`, you call\n  `model(x)`, and the weights are implicit. Define-by-run, imperative.\n- **TensorFlow / Keras** — Keras is the high-level layer API; classic\n  TensorFlow built a static computation graph first and ran it afterwards.\n  Mostly implicit-parameter, like PyTorch.\n- **JAX / Flax** — functional and **explicit-parameter**, the same\n  philosophy as Lux: pure functions with parameters passed in. If you know\n  Flax, Lux will feel familiar.\n\nThe payoff of the Lux convention is uniformity: the `model(x, ps, st)` /\n`Zygote.gradient` / `Optimisers.update` loop above is *byte-for-byte* the\nshape of every training run in this course, plain classifier or PINN alike.\n\n## 2.6 Optimisation {#sec-optimisation}\n\nTraining a neural network — or fitting a PINN — comes down to\n**minimising a scalar loss over a large parameter vector $\\theta\n\\in \\mathbb{R}^P$**, given its gradient $g = \\nabla_\\theta \\mathcal{L}$.\nThis section is about the optimisers that *use* that gradient: plain\ngradient descent and its geometry, the stochastic / mini-batch\nvariants, momentum and Adam, and the quasi-Newton method (L-BFGS)\nthat often finishes the job. *How* the gradient itself is computed —\nautomatic differentiation — is the next section\n([§2.7](#sec-autodiff)).\nMost of this material is treated at greater depth in\n[*Mathematical Engineering of Deep Learning*, Chapter 4 (*Optimization Algorithms*)](../references/references.qmd#ref-liquet2024){target=\"_blank\"},\nour primary reference throughout this unit — with the classic,\nthorough treatment in\n[Goodfellow, Bengio & Courville (2016)](../references/references.qmd#ref-goodfellow2016){target=\"_blank\"}\nChapter 8 as the standard alternative. The goal here is a working\nunderstanding sufficient to read PINN training code and know which\nknob to turn when it doesn't converge.\n\n### Gradient descent: the geometric core\n\nGiven a smooth loss $\\mathcal{L}: \\mathbb{R}^P \\to \\mathbb{R}$ and a\nparameter vector $\\theta_t$, the gradient\n$g_t = \\nabla_\\theta \\mathcal{L}(\\theta_t) \\in \\mathbb{R}^P$ is the\ndirection in which $\\mathcal{L}$ *increases fastest*. **Gradient\ndescent** takes a small step in the opposite direction:\n\n$$\n\\theta_{t+1} \\;=\\; \\theta_t \\;-\\; \\eta\\, g_t,\n$$ {#eq-gd}\n\nwith **learning rate** $\\eta > 0$. To first order in $\\eta$,\n\n$$\n\\mathcal{L}(\\theta_{t+1})\n\\;\\approx\\;\n\\mathcal{L}(\\theta_t) - \\eta\\, \\|g_t\\|^2 + O(\\eta^2),\n$$\n\nso any positive $\\eta$ decreases the loss locally; too large and\nthe $O(\\eta^2)$ Hessian term wins and the iterate *diverges*. The\npractical learning-rate range for deep networks ($10^{-4}$ to\n$10^{-2}$) is set by this balance — see *MEDL*\n[Chapter 4](../references/references.qmd#ref-liquet2024){target=\"_blank\"} for\nthe convergence analysis.\n\n**Why isn't plain gradient descent enough?** Three failure modes\nthat recur throughout deep learning *and* PINN training:\n\n1. **Pathological curvature.** Loss surfaces often have long, thin\n   valleys (the *ravine* problem). $g_t$ points across the valley,\n   not along it. Plain GD zig-zags.\n2. **Bad scaling between parameters.** Different layers have\n   wildly different gradient magnitudes. A single global $\\eta$\n   can't be right for all of them at once.\n3. **Stochastic noise** when $g_t$ is estimated from a mini-batch\n   rather than the full dataset (covered below).\n\nEach of momentum, Adam, and L-BFGS is a different fix.\n\n### Stochastic and mini-batch gradient descent\n\nFor empirical risk $\\mathcal{L}(\\theta) = \\frac{1}{N}\\sum_i \\ell_i(\\theta)$,\nthe **full-batch** gradient sums over all $N$ training examples — exact,\nbut expensive when $N \\in [10^4, 10^9]$. **Stochastic gradient\ndescent (SGD)** replaces the sum with a single random example $i_t$:\n\n$$\n\\theta_{t+1} \\;=\\; \\theta_t - \\eta \\, \\nabla_\\theta \\ell_{i_t}(\\theta_t),\n$$\n\na noisy but unbiased estimator of the true gradient. The middle ground\nis **mini-batch SGD** — sum over a random subset $B \\subset \\{1, \\ldots, N\\}$\nof size $|B|$ (typically 32 – 1024):\n\n$$\n\\theta_{t+1} \\;=\\; \\theta_t - \\frac{\\eta}{|B|}\\sum_{i \\in B}\n                   \\nabla_\\theta \\ell_i(\\theta_t).\n$$\n\nThe gradient variance falls like $1/|B|$. Three reasons mini-batches\ndominate practice:\n\n- **Computational cost.** A modern GPU/TPU is massively\n  parallel; cost per gradient is roughly constant up to $|B| \\sim$\n  hundreds. So a single mini-batch update is nearly as cheap as a\n  single SGD update but with far lower variance.\n- **Gradient noise as a regulariser.** Noisy gradients prevent the\n  iterate from settling into sharp minima; flat minima generalise\n  better empirically. See *MEDL* [Chapter 4](../references/references.qmd#ref-liquet2024){target=\"_blank\"}.\n- **Memory.** Full-batch gradients on a million-example dataset\n  don't fit on a GPU.\n\nPINNs *invert* this picture: their \"dataset\" is a few thousand\ncollocation points, so **full-batch L-BFGS** is feasible and usually\nwins. But every PINN training loop still uses mini-batches for the\nfirst phase (Adam), so the vocabulary matters.\n\n### Momentum and Adam\n\n**SGD + momentum** (Polyak 1964; Sutskever et al. 2013) adds inertia:\n\n$$\n\\begin{aligned}\nv_{t+1} &= \\mu\\, v_t + g_t, \\\\\n\\theta_{t+1} &= \\theta_t - \\eta\\, v_{t+1},\n\\end{aligned}\n$$\n\nwith momentum coefficient $\\mu \\in [0, 1)$ (typically $0.9$). The\nupdate $v_t$ is an exponentially-weighted moving average of past\ngradients — it cancels in directions where successive $g_t$\noscillate (the ravine), and accumulates in directions where they\nagree (the valley floor). For a quadratic loss with condition\nnumber $\\kappa$, momentum reduces the iterations to converge from\n$O(\\kappa)$ to $O(\\sqrt{\\kappa})$ — a square-root speedup.\n\n**Adam** (Kingma & Ba 2015)\ncombines momentum with **per-parameter step sizes** based on the\n*magnitude* of recent gradients:\n\n$$\n\\begin{aligned}\nm_t &= \\beta_1\\, m_{t-1} + (1 - \\beta_1)\\, g_t,\n   &\\hat{m}_t &= \\frac{m_t}{1 - \\beta_1^t}, \\\\\nv_t &= \\beta_2\\, v_{t-1} + (1 - \\beta_2)\\, g_t^2,\n   &\\hat{v}_t &= \\frac{v_t}{1 - \\beta_2^t}, \\\\\n\\theta_{t+1} &= \\theta_t - \\eta \\, \\frac{\\hat{m}_t}{\\sqrt{\\hat{v}_t} + \\varepsilon}.\n\\end{aligned}\n$$\n\nRead as: $\\hat{m}_t$ is the (bias-corrected) running average of the\ngradient (the \"momentum part\"), $\\hat{v}_t$ is the running average\nof the *squared* gradient component-wise (the \"scale part\"), and\nthe update divides one by the square root of the other so that each\nparameter gets a step size inversely proportional to how loud its\nhistorical gradient has been. The bias correction\n($/(1 - \\beta_1^t)$, $/(1 - \\beta_2^t)$) fixes the initial-transient\nunderestimate when $m_0 = v_0 = 0$.\n\nHyperparameter defaults — what *MEDL* [Chapter 4](../references/references.qmd#ref-liquet2024){target=\"_blank\"} recommends and the\nworkshop scripts use: $\\eta \\in [10^{-4}, 10^{-2}]$, $\\beta_1 =\n0.9$, $\\beta_2 = 0.999$, $\\varepsilon = 10^{-8}$. Adam *almost\nalways works*; it is the right first move for any neural-network\ntraining, including the initial phase of every PINN in\n[Units 5–7](../unit_05/unit_05.qmd).\n\n### L-BFGS: quasi-Newton for the small-batch regime\n\nNewton's method takes step $\\theta_{t+1} = \\theta_t - H_t^{-1} g_t$,\nusing the Hessian $H_t = \\nabla_\\theta^2 \\mathcal{L}$. In one step\non a quadratic loss it lands at the minimum. The catch: $H_t$ is\n$P \\times P$ and inverting it costs $O(P^3)$ — infeasible for\n$P \\gtrsim 10^4$ parameters.\n\n**BFGS** builds a positive-definite approximation $B_t \\approx H_t$\nincrementally from successive gradient differences using a rank-2\nupdate. **L-BFGS** (Liu & Nocedal 1989) is the\n*limited-memory* variant: store only the last $m$ pairs of $(s_k,\ny_k) = (\\theta_{k+1} - \\theta_k, \\, g_{k+1} - g_k)$ and reconstruct\n$B_t^{-1} g_t$ implicitly in $O(mP)$ time. Default $m = 10$ — so\nL-BFGS uses ~$10 P$ memory and ~$10 P$ work per step. Crucially:\n\n- **No learning rate to tune.** L-BFGS does an internal Wolfe line\n  search.\n- **Quadratic convergence near the minimum.** Once close, it\n  finishes in a handful of steps.\n- **Needs an accurate gradient.** L-BFGS *assumes* the gradient is\n  deterministic — feed it a noisy mini-batch gradient and the\n  Wolfe conditions break.\n\nThis is exactly the regime PINNs land in: a few thousand\ncollocation points (small enough to take the full-batch gradient\non every step), a non-convex but locally well-conditioned loss\nafter Adam has done the rough work. The recipe across\n[Units 5–7](../unit_05/unit_05.qmd) is therefore:\n\n> **Adam** for a few thousand iterations (escape bad\n> initialisations under mini-batch noise) → **L-BFGS** for\n> a few hundred iterations (drive the residual to convergence with\n> exact gradients).\n\n::: {#ex-2-6 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — race the optimisers down a ravine\n\nImplement gradient descent, momentum ($\\mu = 0.9$), and Adam *by\nhand* — each is under ten lines — and race them on the Rosenbrock\nfunction $f(x, y) = (1 - x)^2 + 100\\,(y - x^2)^2$ from\n$(-1.5, 2)$. Plot the three trajectories over the loss contours and\nthe loss-vs-iteration curves (log scale, 5 000 iterations, tune\neach learning rate to the largest stable value). Which method\nzig-zags across the valley, which one tracks the valley floor, and\nwhere does Adam's per-parameter scaling visibly help?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\nRosenbrock gradient (the part that's easy to get wrong): `∇f(x, y) = [-2(1 - x) - 400x*(y - x^2), 200*(y - x^2)]`. Keep each optimiser under ten lines by mutating the iterate in place with state in a NamedTuple — GD is `x .-= η .* g`; momentum is `v .= μ .* v .+ g; x .-= η .* v`; Adam is the bias-corrected `m`/`v` pair from §2.6 as `x .-= η .* m̂ ./ (sqrt.(v̂) .+ 1e-8)`. The real work is fair tuning: push each `η` up until it just diverges, then back off (GD lands near `1e-3`, Adam near `2e-2`, `μ = 0.9`). Plot `log10 ∘ f` for the contours or the colour scale saturates, then map what you see onto the three §2.6 failure modes.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-6)\n:::\n:::\n\n## 2.7 Automatic differentiation {#sec-autodiff}\n\nEvery optimiser in §2.6 needs the gradient $\\nabla_\\theta \\mathcal{L}$, and so\nfar we have taken it \"for free.\" This section is *how* you get it — and it\nmatters more for PINNs than for ordinary deep learning, because a PINN\ndifferentiates its own network *inside* the loss.\n\n**Automatic differentiation is neither of the two things people first guess.**\nIt is *not* symbolic differentiation (manipulating formulas, which blows up in\nsize), and it is *not* finite differences\n$\\bigl(f(x+h)-f(x)\\bigr)/h$ (which forces a bad trade between truncation error at\nlarge $h$ and round-off at small $h$). Instead it computes the **exact**\nderivative — to machine precision — by applying the chain rule to the elementary\noperations your code already runs. There are two ways to do it.\n\n### Computational graphs and backprop\n\nEvery neural-network loss is the output of a finite computation\ngraph — a DAG whose nodes are tensors and whose edges are\nelementary operations.\n\n![A small computational graph. Forward evaluation flows left-to-right; reverse-mode AD (backpropagation) populates gradients right-to-left. (Figure from *MEDL*, §4.4.)](figures/figure4-7-computational_graph.svg)\n\n**Backpropagation** is exactly reverse-mode automatic\ndifferentiation applied to that graph: one forward pass evaluates\nintermediate quantities, one backward pass propagates gradients\nusing the chain rule. Cost is $O(\\text{nodes})$ per gradient — i.e.,\nsimilar to one forward pass.\n\n### Dual numbers and the tape\n\n**Forward mode = dual numbers.** Carry each value together with its derivative as\na pair $(x, \\dot x)$. Formally, adjoin a symbol $\\varepsilon$ with\n$\\varepsilon^2 = 0$ and evaluate $f$ at $a + \\varepsilon$: every elementary rule\ngives $f(a + \\varepsilon) = f(a) + f'(a)\\,\\varepsilon$, so the coefficient of\n$\\varepsilon$ that drops out the far end *is* the derivative. `ForwardDiff.jl` is\nexactly this — no formulas, no step size:\n\n```{.julia}\nusing ForwardDiff\n\nf(x) = sin(x^2)\nForwardDiff.derivative(f, 1.0)            # 1.08060…  (= 2x·cos(x²) at x=1, exact)\n\ng(v) = sum(v .^ 2)\nForwardDiff.gradient(g, [1.0, 2.0, 3.0])  # [2.0, 4.0, 6.0]\n```\n\nOne forward pass carries one derivative direction, so a full gradient costs about\n$n$ passes for $n$ inputs — cheap when $n$ is small.\n\n**Reverse mode = the tape (backpropagation).** Record every elementary operation\non the forward pass — that is the \"tape\", i.e. the computational graph above —\nthen walk it **backwards once**, accumulating the adjoint\n$\\partial\\mathcal{L}/\\partial(\\text{each node})$ by the chain rule. A *single*\nbackward pass produces the gradient with respect to **all** inputs at once, at a\ncost of roughly one forward evaluation — *independent of how many parameters\nthere are*. `Zygote.jl` does this:\n\n```{.julia}\nusing Zygote\n\ng(v) = sum(v .^ 2)\nZygote.gradient(g, [1.0, 2.0, 3.0])[1]    # [2.0, 4.0, 6.0] — same answer, one backward pass\n```\n\n**So which mode?** For $f:\\mathbb{R}^n \\to \\mathbb{R}^m$, forward mode costs\n$\\propto n$ and reverse mode $\\propto m$. Training a network is \"millions of\nparameters in, one scalar loss out\" ($n$ huge, $m = 1$), so **reverse mode wins**\n— which is why backprop, and every deep-learning framework, is reverse-mode AD.\n\n### Differentiating the network itself: forward-over-reverse (the PINN twist)\n\nPINNs add something ordinary deep learning never does: the loss contains\n**derivatives of the network's output with respect to its inputs**. For a network\n$u(x;\\theta)$ standing in for a PDE solution, the residual needs spatial\nderivatives like $u_x, u_{xx}$ at each collocation point — and we *still* need the\ngradient of that loss with respect to the parameters $\\theta$. Two\ndifferentiations, nested.\n\n**The inner derivative — network output w.r.t. its input.** Few inputs ($x$,\nmaybe $t$), often to second order or higher: exactly where forward mode shines,\nand it **nests** — just differentiate the derivative:\n\n```{.julia}\nusing ForwardDiff\n\nu(x)  = sin(2x) * exp(-x)               # pretend this is the network output u(x)\nu1(x) = ForwardDiff.derivative(u, x)\nu2(x) = ForwardDiff.derivative(u1, x)  # nest forward mode → the 2nd derivative\n\nu2(0.3)    # -3.7006…  (matches the hand derivative e^{-x}(-3 sin 2x - 4 cos 2x))\n```\n\nThat `u2` is precisely the operator a diffusion or Poisson PINN puts in its\nresidual ([Unit 5](../unit_05/unit_05.qmd)). It is also why §2.4's ReLU warning\nbites: a ReLU network's second derivative is zero almost everywhere, so the\nresidual can't even be formed.\n\n**The outer gradient — loss w.r.t. parameters.** Sum the residual over collocation\npoints into a scalar loss and differentiate w.r.t. the parameters. Here is the\nwhole shape on a tiny three-parameter stand-in \"network\"\n$u(x;p) = p_1 \\sin(p_2 x) + p_3$, asked to satisfy $u'' = -\\pi^2 \\sin(\\pi x)$:\n\n```{.julia}\nusing ForwardDiff\n\nunet(x, p) = p[1] * sin(p[2] * x) + p[3]\nuxx(x, p)  = ForwardDiff.derivative(z -> ForwardDiff.derivative(y -> unet(y, p), z), x)\n\nxs   = range(0, 1; length = 20)\nloss(p) = sum((uxx(x, p) + pi^2 * sin(pi * x))^2 for x in xs)   # PDE residual, summed\n\nForwardDiff.gradient(loss, [1.0, 3.0, 0.0])   # ∇ₚ loss = [-108.8, -143.7, 0.0]\n```\n\nThat gradient drives the optimiser (Adam, then L-BFGS) just like every other fit\nin this unit — the *only* new ingredient is that `loss` had a derivative of the\nnetwork inside it.\n\n**Forward-over-reverse, and what SciML actually uses.** Both differentiations\nabove use forward mode because the toy has just three parameters. A real PINN has\n*thousands*, so the **outer** parameter-gradient switches to **reverse mode**\n(cheap when $m=1$ over many parameters) while the **inner** input-derivative stays\n**forward mode** (cheap for one or two inputs). That composition — a reverse-mode\ngradient of a loss that contains forward-mode input-derivatives — is\n**forward-over-reverse**, and getting the nesting right is the difference between a\nPINN that trains in minutes and one that crawls.\n\nYou won't assemble this by hand. `NeuralPDE.jl` builds the residual and its\nderivatives for you, layered on `Lux.jl` (the network), `ForwardDiff.jl` (the\ninput derivatives), and reverse-mode AD (`Zygote.jl`, increasingly `Enzyme.jl`)\nfor the parameter gradient — with `ChainRules.jl` supplying the rules that let the\nmodes compose. Picking and nesting these backends correctly is a large part of\nwhat the SciML stack does so that the residual you write in maths comes out\ndifferentiated correctly *and* fast.\n\n::: {#ex-2-7 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — differentiate a network's output, then its loss\n\nNo training — just the autodiff. **(a)** For $u(x) = e^{\\sin x}$, compute\n$u''(0.7)$ by nesting `ForwardDiff.derivative` twice, and check it against the\nhand derivative $u'' = (\\cos^2 x - \\sin x)\\,e^{\\sin x}$. **(b)** Now the\nforward-over-reverse shape: take the toy \"network\" $u(x; p) = p_1 \\tanh(p_2 x)$,\nform the residual loss\n$\\mathcal{L}(p) = \\sum_i \\bigl(u''(x_i; p) + u(x_i; p)\\bigr)^2$ over ten points\n$x_i \\in [0, 1]$ (so it wants $u'' = -u$, the oscillator), and compute\n$\\nabla_p \\mathcal{L}$ — once with `ForwardDiff.gradient` and once by a\nfinite-difference check on each component. They should agree. Finally: once $p$\nhas *thousands* of entries, which mode would you switch the **outer** pass to,\nand why?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\nThe second derivative is `ForwardDiff.derivative(t -> ForwardDiff.derivative(u, t), x)`. For (b), `uxx(x, p)` nests the same way over the spatial argument while carrying `p`; then `ForwardDiff.gradient(loss, p)` is the whole parameter gradient at once. The finite-difference check is `(loss(p .+ h .* eᵢ) - loss(p)) / h` with `h = 1e-6`. For the last part, count inputs vs outputs: reverse mode is the cheap direction when there are many parameters and one scalar loss.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-7)\n:::\n:::\n\n## 2.8 Training a model in practice\n\nThe previous sections set up everything we need — a function class\n(MLP), an autodiff engine, an optimiser, and a dataset (MNIST) with\ntwo known baselines (random forest ~97%, softmax regression ~92%).\nNow we train *real* networks on MNIST and close the gap. We lead with\nthe strongest, most genuinely-Julia piece — a **convolutional network in\n`Lux.jl`**, trained on CPU and GPU — then step back to a plain **MLP** to\nsee how the GPU payoff scales, and finally show the same MLP in the\nPython ecosystem (`scikit-learn`, `PyTorch`) for the cross-language\ncomparison. The Julia runs are the ones we execute (they fetch MNIST\ndirectly, so they need no extra dataset package); the Python listings are\nstatic.\n\n### A convolutional network on MNIST (Lux.jl) {#sec-mnist-cnn}\n\nThe softmax classifier (§2.3) and the MLP both *flatten* each\n$28 \\times 28$ image into a length-784 vector — they throw the 2-D\nstructure away before they ever see it. A **convolutional network** keeps\nit: each conv layer slides small learnable filters across the image,\nsharing one set of weights over every location.\n\nThat weight sharing is a textbook **inductive bias** — an assumption\nabout the problem, baked into the *architecture*, that biases the model\ntoward the right kind of solution before it sees any data. A convolution\nassumes two things about images: *locality* (nearby pixels are what\nmatter) and *translation invariance* (an edge or stroke means the same\nthing wherever it sits, so one filter should detect it everywhere).\nEncoding those assumptions in the architecture means the network doesn't\nhave to *learn* them — so it needs far fewer parameters and generalises\nbetter. Hold onto this idea, because it is exactly how **PINNs** work too:\nthere the inductive bias is the *PDE itself*, wired into the loss, telling\nthe network what physics the solution must satisfy\n(§2.10, [Unit 5](../unit_05/unit_05.qmd)). A CNN biases the model toward\nimage structure; a PINN biases it toward physics — same principle, with\nthe prior coming from a law of nature instead of an architecture.\nConvolutional networks are the subject of\n[*Mathematical Engineering of Deep Learning*, Chapter 6 (*Convolutional Neural Networks*)](../references/references.qmd#ref-liquet2024){target=\"_blank\"}.\n\nThe script below is the classic **LeNet-5** (LeCun et al., 1998) in\n`Lux.jl` — two `Conv` + `MaxPool` blocks that learn 2-D features, then\nthree `Dense` layers that classify them — trained on the same MNIST\ndata, on the CPU and the GPU:\n\n```{.julia filename=\"units/unit_02/scripts/conv_mnist_lux.jl\" code-fold=\"true\" code-summary=\"Show the LeNet-5 convolutional network\"}\n#!/usr/bin/env julia\n# ===========================================================================\n# Unit 2.7 — a convolutional network in Lux.jl (LeNet-5 on MNIST).\n#\n# A real, multi-layer CONVOLUTIONAL network — the architecture family of\n# *Mathematical Engineering of Deep Learning* Chapter 6 (Convolutional Neural\n# Networks), and the headline model of §2.7. It is the classic LeNet-5\n# (LeCun et al., 1998): two conv+pool blocks that learn local 2-D features,\n# then three dense layers that classify them.\n#\n# Why convolutions? The softmax (§2.3) and MLP (§2.7) flatten each 28×28 image\n# to a length-784 vector, throwing away the 2-D spatial structure. A conv layer\n# instead slides small learnable filters over the image, sharing weights across\n# locations — far fewer parameters, and translation-aware. On the same MNIST\n# data that gave us random forest ~97%, softmax ~92% and the MLP ~98%, the CNN\n# reaches ~98.8%, the best in the unit.\n#\n# Convolutions are also where the GPU really earns its keep: each layer is many\n# small matmuls, so the per-epoch speed-up is much larger than the MLP's ~3×.\n#\n# Run on the GPU hub (the @pinn env has Lux + LuxCUDA + cuDNN + CUDA):\n#   julia --project=@pinn units/unit_02/scripts/conv_mnist_lux.jl\n# Nothing here runs during `quarto render` — the .qmd shows it `eval: false`.\n# ===========================================================================\n\nusing Lux, LuxCUDA, CUDA, Optimisers, Zygote, Random, Printf, Statistics, Downloads\n\n# --- MNIST loader (direct download + pure-Julia IDX parse) → image tensors ---\nconst MIRRORS = [\"https://storage.googleapis.com/cvdf-datasets/mnist/\",\n                 \"https://ossci-datasets.s3.amazonaws.com/mnist/\"]\n\nfunction fetch_idx(name)\n    cache = joinpath(get(ENV, \"MNIST_DIR\", \"/tmp/mnist\"), name)\n    raw   = replace(cache, \".gz\" => \"\")\n    isdir(dirname(cache)) || mkpath(dirname(cache))\n    if !isfile(raw)\n        ok = false\n        for m in MIRRORS\n            try\n                Downloads.download(m * name, cache); ok = true; break\n            catch; end\n        end\n        ok || error(\"could not download $name from any mirror\")\n        run(`gunzip -f $cache`)\n    end\n    return read(raw)\nend\n\nfunction load_mnist()\n    function images(name)\n        b  = fetch_idx(name)\n        n  = Int(b[5])<<24 | Int(b[6])<<16 | Int(b[7])<<8 | Int(b[8])\n        nr = Int(b[9])<<24 | Int(b[10])<<16 | Int(b[11])<<8 | Int(b[12])\n        nc = Int(b[13])<<24 | Int(b[14])<<16 | Int(b[15])<<8 | Int(b[16])\n        # Lux/cuDNN want WHCN: (width, height, channels, batch)\n        return reshape(Float32.(b[17:end]) ./ 255f0, nr, nc, 1, n)\n    end\n    function labels(name)\n        b = fetch_idx(name)\n        n = Int(b[5])<<24 | Int(b[6])<<16 | Int(b[7])<<8 | Int(b[8])\n        return Int.(b[9:8+n])                  # 0..9\n    end\n    Xtr = images(\"train-images-idx3-ubyte.gz\"); ytr = labels(\"train-labels-idx1-ubyte.gz\")\n    Xte = images(\"t10k-images-idx3-ubyte.gz\");  yte = labels(\"t10k-labels-idx1-ubyte.gz\")\n    return Xtr, ytr, Xte, yte\nend\n\nonehot(y) = (Y = zeros(Float32, 10, length(y)); for (j, c) in enumerate(y); Y[c+1, j] = 1f0; end; Y)\n\n# numerically-stable softmax cross-entropy (works on Array or CuArray)\nfunction logitce(logits, Y)\n    m  = maximum(logits; dims = 1)\n    ls = logits .- m .- log.(sum(exp.(logits .- m); dims = 1))\n    return -sum(Y .* ls) / size(Y, 2)\nend\n\n# LeNet-5: conv→pool→conv→pool→dense×3. ~62k parameters.\nmake_cnn() = Chain(\n    Conv((5, 5), 1 => 6, relu, pad = 2),   # 28×28×6\n    MaxPool((2, 2)),                        # 14×14×6\n    Conv((5, 5), 6 => 16, relu),            # 10×10×16\n    MaxPool((2, 2)),                        #  5×5×16\n    FlattenLayer(),                         # 400\n    Dense(400 => 120, relu),\n    Dense(120 => 84, relu),\n    Dense(84 => 10),\n)\n\nfunction accuracy(model, ps, st, X, y, dev; bs = 1000)\n    correct = 0\n    for s in 1:bs:size(X, 4)\n        idx = s:min(s + bs - 1, size(X, 4))\n        ŷ, _ = model(dev(X[:, :, :, idx]), ps, st)\n        pred = vec(map(i -> i[1] - 1, argmax(Array(ŷ); dims = 1)))\n        correct += sum(pred .== y[idx])\n    end\n    return correct / length(y)\nend\n\n# one mini-batch SGD/Adam epoch; returns updated (ps, opt)\nfunction train_epoch!(model, ps, st, opt, Xd, Yd, n, bs)\n    order = randperm(n)\n    for s in 1:bs:n\n        idx = order[s:min(s + bs - 1, n)]\n        xb = Xd[:, :, :, idx]; yb = Yd[:, idx]\n        gs = Zygote.gradient(p -> logitce(first(model(xb, p, st)), yb), ps)[1]\n        opt, ps = Optimisers.update(opt, ps, gs)\n    end\n    return ps, opt\nend\n\n# ---------------------------------------------------------------------------\nprintln(\"=\"^64); println(\"Unit 2.7 — MNIST convolutional network (LeNet-5, Lux.jl)\"); println(\"=\"^64)\nhave_gpu = CUDA.functional()\n@printf(\"GPU available: %s%s\\n\", have_gpu, have_gpu ? \"  ($(CUDA.name(CUDA.device())))\" : \"\")\n\nprint(\"loading MNIST … \"); Xtr, ytr, Xte, yte = load_mnist()\nYtr = onehot(ytr)\n@printf(\"train=%d  test=%d  (28×28×1 image tensors)\\n\", size(Xtr, 4), size(Xte, 4))\n@printf(\"LeNet-5: 2 conv blocks + 3 dense layers, %d parameters\\n\\n\", Lux.parameterlength(make_cnn()))\nconst BS = 128\n\n# --- per-epoch wall-clock: CPU vs GPU (convolutions favour the GPU heavily) --\nprintln(\"Per-epoch wall-clock (batch=$BS, full 60k train set):\")\n@printf(\"%-8s %12s\\n\", \"device\", \"sec / epoch\"); println(\"-\"^24)\nresults = Dict{String,Float64}()\nfor (tag, dev) in (have_gpu ? ((\"CPU\", identity), (\"GPU\", gpu_device())) : ((\"CPU\", identity),))\n    rng = Xoshiro(0)\n    model = make_cnn(); ps, st = Lux.setup(rng, model)\n    ps = ps |> dev; st = st |> dev\n    Xd = Xtr |> dev; Yd = Ytr |> dev\n    ps, _ = train_epoch!(model, ps, st, Optimisers.setup(Adam(1f-3), ps), Xd, Yd, size(Xtr,4), BS) # warmup/compile\n    dev === identity || CUDA.synchronize()\n    t0 = time()\n    ps, _ = train_epoch!(model, ps, st, Optimisers.setup(Adam(1f-3), ps), Xd, Yd, size(Xtr,4), BS)\n    dev === identity || CUDA.synchronize()\n    results[tag] = time() - t0\n    @printf(\"%-8s %12.2f\\n\", tag, results[tag])\nend\nif haskey(results, \"GPU\")\n    @printf(\"\\nGPU speed-up: %.1fx per epoch (vs the MLP's ~3x — convolutions are far more compute-dense)\\n\",\n            results[\"CPU\"] / results[\"GPU\"])\nend\n\n# --- a full training run on the GPU (or CPU fallback) to real accuracy -------\ndev = have_gpu ? gpu_device() : identity\nprintln(\"\\nFull training run on $(have_gpu ? \"GPU\" : \"CPU\") — 10 epochs:\")\nrng = Xoshiro(1); model = make_cnn(); ps, st = Lux.setup(rng, model)\nps = ps |> dev; st = st |> dev\nXd = Xtr |> dev; Yd = Ytr |> dev\nopt = Optimisers.setup(Adam(1f-3), ps)\nhist = Float64[]\nfor epoch in 1:10\n    global ps, opt = train_epoch!(model, ps, st, opt, Xd, Yd, size(Xtr,4), BS)\n    acc = accuracy(model, ps, st, Xte, yte, dev)\n    push!(hist, acc)\n    @printf(\"  epoch %2d   test accuracy = %.4f\\n\", epoch, acc)\nend\n@printf(\"\\nFinal MNIST test accuracy: %.4f  (forest ~0.97, softmax ~0.92, MLP ~0.98)\\n\", hist[end])\n\n```\n\nCaptured on the workshop GPU hub (NVIDIA L4):\n\n::: {.cell-output .cell-output-stdout}\n```text\n================================================================\nUnit 2.7 — MNIST convolutional network (LeNet-5, Lux.jl)\n================================================================\nGPU available: true  (NVIDIA L4)\nloading MNIST … train=60000  test=10000  (28×28×1 image tensors)\nLeNet-5: 2 conv blocks + 3 dense layers, 61706 parameters\n\nPer-epoch wall-clock (batch=128, full 60k train set):\ndevice    sec / epoch\n------------------------\nCPU             21.18\nGPU              1.33\n\nGPU speed-up: 16.0x per epoch (vs the MLP's ~3x — convolutions are far more compute-dense)\n\nFull training run on GPU — 10 epochs:\n  epoch  1   test accuracy = 0.9721\n  epoch  2   test accuracy = 0.9789\n  epoch  3   test accuracy = 0.9843\n  epoch  4   test accuracy = 0.9864\n  epoch  5   test accuracy = 0.9870\n  epoch  6   test accuracy = 0.9848\n  epoch  7   test accuracy = 0.9895\n  epoch  8   test accuracy = 0.9861\n  epoch  9   test accuracy = 0.9886\n  epoch 10   test accuracy = 0.9875\n\nFinal MNIST test accuracy: 0.9875  (forest ~0.97, softmax ~0.92, MLP ~0.98)\n```\n:::\n\n\nTwo payoffs. First, **accuracy**: the CNN reaches **~98.8%** — the best\nin the unit, topping the random forest (~97%) and the softmax baseline\n(~92%), and edging out the plain MLP (~98%) we train next. And it does so\nwith **61,706 parameters — fewer than a quarter of that MLP's 235,146**:\nthe convolution's inductive bias buys *more* accuracy with *fewer*\nweights — the opposite of the \"depth costs parameters\" trade a plain MLP\nmakes. Second, **the GPU**: because a CNN is many small matmuls per layer\nit is far more compute-dense than a flat MLP, so the per-epoch speed-up\nhere is **~16×** — far above what the same card gives the small dense MLP\n(~3×, which we see next). Convolutions are where the GPU starts to matter,\nand the collocation counts of PINNs (from\n[Unit 5](../unit_05/unit_05.qmd)) push that lever harder still.\n\n### Training on the GPU — the same one-liner on a plain MLP (Julia, Lux + CUDA) {#sec-mnist-gpu}\n\nNow step down to a simpler model — a plain **MLP** (the §2.3 softmax grown\ntwo hidden layers, `784 → 256 → 128 → 10`) — which makes it easy to see\n*how the GPU's advantage scales with the model*. The same MLP is trained\non the CPU and on the GPU, where the only change is pushing the parameters\nand the data to the device with `|> gpu_device()`. Everything else — the\nmodel, the loss, the Adam update — is byte-for-byte identical.\n\n```{.julia filename=\"units/unit_02/scripts/mnist_gpu_lux.jl\" code-fold=\"true\" code-summary=\"Show the GPU MNIST trainer\"}\n#!/usr/bin/env julia\n# ===========================================================================\n# Unit 2.7 — a real deep-learning training run on the GPU (MNIST, Lux.jl).\n#\n# Section 2.7 trains an MLP on MNIST in scikit-learn and PyTorch. The PyTorch\n# version already moves tensors to `cuda`; this\n# is the *Julia* side of that story: the identical Lux model trained on the CPU\n# and on the GPU, so you can see (a) that the move is a one-liner — push the\n# params and the data to the device — and (b) the speed-up on an image-scale\n# dataset where the GPU's batched matmuls actually pay off.\n#\n# MNIST is fetched directly from a public mirror and parsed in a few lines of\n# pure Julia (no MLDatasets / PyCall dependency). Model: 784-256-128-10 MLP.\n#\n# Run on the GPU hub (the @pinn env has Lux + LuxCUDA + cuDNN + CUDA):\n#   julia --project=@pinn units/unit_02/scripts/mnist_gpu_lux.jl\n# Nothing here runs during `quarto render` — the .qmd shows it `eval: false`.\n# ===========================================================================\n\nusing Lux, LuxCUDA, CUDA, Optimisers, Zygote, Random, Printf, Statistics, Downloads\n\n# --- MNIST loader (direct download + pure-Julia IDX parse) -----------------\nconst MIRRORS = [\"https://storage.googleapis.com/cvdf-datasets/mnist/\",\n                 \"https://ossci-datasets.s3.amazonaws.com/mnist/\"]\n\nfunction fetch_idx(name)\n    cache = joinpath(get(ENV, \"MNIST_DIR\", \"/tmp/mnist\"), name)\n    raw   = replace(cache, \".gz\" => \"\")\n    isdir(dirname(cache)) || mkpath(dirname(cache))\n    if !isfile(raw)\n        ok = false\n        for m in MIRRORS\n            try\n                Downloads.download(m * name, cache); ok = true; break\n            catch; end\n        end\n        ok || error(\"could not download $name from any mirror\")\n        run(`gunzip -f $cache`)\n    end\n    return read(raw)\nend\n\nfunction load_mnist()\n    function images(name)\n        b = fetch_idx(name)\n        n  = Int(b[5])<<24 | Int(b[6])<<16 | Int(b[7])<<8 | Int(b[8])\n        nr = Int(b[9])<<24 | Int(b[10])<<16 | Int(b[11])<<8 | Int(b[12])\n        nc = Int(b[13])<<24 | Int(b[14])<<16 | Int(b[15])<<8 | Int(b[16])\n        px = reshape(b[17:end], nr*nc, n)\n        return Float32.(px) ./ 255f0          # (784, n), normalised\n    end\n    function labels(name)\n        b = fetch_idx(name)\n        n = Int(b[5])<<24 | Int(b[6])<<16 | Int(b[7])<<8 | Int(b[8])\n        return Int.(b[9:8+n])                  # 0..9\n    end\n    Xtr = images(\"train-images-idx3-ubyte.gz\"); ytr = labels(\"train-labels-idx1-ubyte.gz\")\n    Xte = images(\"t10k-images-idx3-ubyte.gz\");  yte = labels(\"t10k-labels-idx1-ubyte.gz\")\n    return Xtr, ytr, Xte, yte\nend\n\nonehot(y) = (Y = zeros(Float32, 10, length(y)); for (j, c) in enumerate(y); Y[c+1, j] = 1f0; end; Y)\n\n# numerically-stable softmax cross-entropy (works on Array or CuArray)\nfunction logitce(logits, Y)\n    m  = maximum(logits; dims = 1)\n    ls = logits .- m .- log.(sum(exp.(logits .- m); dims = 1))\n    return -sum(Y .* ls) / size(Y, 2)\nend\n\nfunction accuracy(model, ps, st, X, y, dev)\n    ŷ, _ = model(dev(X), ps, st)\n    pred = vec(map(i -> i[1] - 1, argmax(Array(ŷ); dims = 1)))\n    return mean(pred .== y)\nend\n\n# --- one training epoch (mini-batch SGD/Adam); returns seconds --------------\nfunction train_epoch!(model, ps, st, opt, Xd, Yd, n, bs)\n    order = randperm(n)\n    for s in 1:bs:n\n        idx = order[s:min(s+bs-1, n)]\n        xb = Xd[:, idx]; yb = Yd[:, idx]\n        gs = Zygote.gradient(p -> logitce(first(model(xb, p, st)), yb), ps)[1]\n        opt, ps = Optimisers.update(opt, ps, gs)\n    end\n    return ps, opt\nend\n\n# ---------------------------------------------------------------------------\nprintln(\"=\"^64); println(\"Unit 2.7 — MNIST MLP training on CPU vs GPU (Lux.jl)\"); println(\"=\"^64)\nhave_gpu = CUDA.functional()\n@printf(\"GPU available: %s%s\\n\", have_gpu, have_gpu ? \"  ($(CUDA.name(CUDA.device())))\" : \"\")\n\nprint(\"loading MNIST … \"); Xtr, ytr, Xte, yte = load_mnist()\nYtr = onehot(ytr)\n@printf(\"train=%d  test=%d  (28x28 → 784)\\n\\n\", size(Xtr, 2), size(Xte, 2))\n\nmake_model() = Chain(Dense(784 => 256, relu), Dense(256 => 128, relu), Dense(128 => 10))\nconst BS = 128\n\n# --- per-epoch wall-clock: CPU vs GPU (same model, same data) --------------\nprintln(\"Per-epoch wall-clock (batch=$BS, full 60k train set):\")\n@printf(\"%-8s %12s\\n\", \"device\", \"sec / epoch\"); println(\"-\"^24)\nresults = Dict{String,Float64}()\nfor (tag, dev) in (have_gpu ? ((\"CPU\", identity), (\"GPU\", gpu_device())) : ((\"CPU\", identity),))\n    rng = Xoshiro(0)\n    model = make_model(); ps, st = Lux.setup(rng, model)\n    ps = ps |> dev; st = st |> dev\n    Xd = Xtr |> dev; Yd = Ytr |> dev\n    ps, _ = train_epoch!(model, ps, st, Optimisers.setup(Adam(1f-3), ps), Xd, Yd, size(Xtr,2), BS) # warmup/compile\n    dev === identity || CUDA.synchronize()\n    t0 = time()\n    ps, _ = train_epoch!(model, ps, st, Optimisers.setup(Adam(1f-3), ps), Xd, Yd, size(Xtr,2), BS)\n    dev === identity || CUDA.synchronize()\n    results[tag] = time() - t0\n    @printf(\"%-8s %12.2f\\n\", tag, results[tag])\nend\nif haskey(results, \"GPU\")\n    @printf(\"\\nGPU speed-up: %.1fx per epoch\\n\", results[\"CPU\"] / results[\"GPU\"])\nend\n\n# --- a full training run on the GPU (or CPU fallback) to real accuracy ------\ndev = have_gpu ? gpu_device() : identity\nprintln(\"\\nFull training run on $(have_gpu ? \"GPU\" : \"CPU\") — 10 epochs:\")\nrng = Xoshiro(1); model = make_model(); ps, st = Lux.setup(rng, model)\nps = ps |> dev; st = st |> dev\nXd = Xtr |> dev; Yd = Ytr |> dev\nopt = Optimisers.setup(Adam(1f-3), ps)\nhist = Float64[]\nfor epoch in 1:10\n    global ps, opt = train_epoch!(model, ps, st, opt, Xd, Yd, size(Xtr,2), BS)\n    acc = accuracy(model, ps, st, Xte, yte, dev)\n    push!(hist, acc)\n    @printf(\"  epoch %2d   test accuracy = %.4f\\n\", epoch, acc)\nend\n@printf(\"\\nFinal MNIST test accuracy: %.4f\\n\", hist[end])\n\ntry\n    using CairoMakie\n    f = Figure(size = (560, 380))\n    ax = Axis(f[1, 1], title = \"MNIST MLP on the GPU — test accuracy\",\n              xlabel = \"epoch\", ylabel = \"test accuracy\")\n    lines!(ax, 1:length(hist), hist, linewidth = 3)\n    scatter!(ax, 1:length(hist), hist, markersize = 9)\n    figdir = get(ENV, \"GPU_FIG_DIR\", joinpath(@__DIR__, \"..\", \"figures\"))\n    isdir(figdir) || mkpath(figdir)\n    save(joinpath(figdir, \"mnist_gpu_accuracy.png\"), f)\n    println(\"wrote figures/mnist_gpu_accuracy.png\")\ncatch e\n    println(\"(figure skipped: \", e, \")\")\nend\n\n```\n\nCaptured on the workshop GPU hub (NVIDIA L4):\n\n::: {.cell-output .cell-output-stdout}\n```text\n================================================================\nUnit 2.7 — MNIST MLP training on CPU vs GPU (Lux.jl)\n================================================================\nGPU available: true  (NVIDIA L4)\nloading MNIST … train=60000  test=10000  (28x28 → 784)\n\nPer-epoch wall-clock (batch=128, full 60k train set):\ndevice    sec / epoch\n------------------------\nCPU              2.01\nGPU              0.67\n\nGPU speed-up: 3.0x per epoch\n\nFull training run on GPU — 10 epochs:\n  epoch  1   test accuracy = 0.9616\n  epoch  2   test accuracy = 0.9680\n  epoch  3   test accuracy = 0.9768\n  epoch  4   test accuracy = 0.9780\n  epoch  5   test accuracy = 0.9766\n  epoch  6   test accuracy = 0.9784\n  epoch  7   test accuracy = 0.9791\n  epoch  8   test accuracy = 0.9826\n  epoch  9   test accuracy = 0.9801\n  epoch 10   test accuracy = 0.9796\n\nFinal MNIST test accuracy: 0.9796\n```\n:::\n\n\nTwo things to take away. First, the GPU is about **3× faster per epoch**\nhere — real, but not dramatic, because a 784-wide MLP on 28×28 images is\n*small*: the batched matmuls don't fully occupy the card and the CPU is no\nslouch. That's the flip side of the CNN's **~16×** above — the more\ncompute-dense the model, the more the GPU pulls ahead, and the\ncollocation-point counts that PINNs demand\n([Unit 5](../unit_05/unit_05.qmd)) push it further still. Second, the move\nitself is trivial: one `gpu_device()` and the same code trains on either\nprocessor. The full 10-epoch run reaches **97.96%** test accuracy:\n\n![MNIST test accuracy over 10 training epochs of the Lux MLP, trained on the GPU.](figures/mnist_gpu_accuracy.png)\n\n### Regularisation, batch norm, dropout\n\nThree standard knobs to keep training honest:\n\n- **Weight regularisation** — add $\\lambda \\|\\theta\\|^2$ to the loss\n  ($L_2$, \"weight decay\") to keep the parameters small.\n- **Batch normalisation** — normalise activations within each\n  mini-batch; lets you use higher learning rates and reduces\n  sensitivity to initialisation.\n- **Dropout** — randomly zero a fraction of activations during\n  training; equivalent to averaging over an ensemble of thinned\n  networks.\n\n![Dropout: at each training step, a random subset of hidden units is masked out; at test time all units are used with weights rescaled. (Figure from *MEDL*, §5.7.)](figures/figure5-11-dropout.svg)\n\nFor PINNs the regularisation knobs you care about are *physics\nterms* in the loss rather than weight penalties or dropout — the\nPDE residual itself is a powerful regulariser, as we'll see from\n[Unit 5](../unit_05/unit_05.qmd) onward.\n\n### The same MLP in Python — `scikit-learn`\n\nFor the cross-language picture, here is that same MLP — the\n`784 → 256 → 128 → 10` network we just trained on the GPU above — in the\nPython ecosystem. These listings are **static** — we don't execute them in the\nbuild; they're the Python mirror of the Julia workflow above. First the\nfew-line `scikit-learn` version; expect **~98% test accuracy** —\ncomfortably beating the softmax baseline, edging out the random forest:\n\n```{.python filename=\"units/unit_02/scripts/mnist_mlp_sklearn.py\"}\nfrom sklearn.datasets import fetch_openml\nfrom sklearn.neural_network import MLPClassifier\nfrom sklearn.metrics import accuracy_score\n\nX, y = fetch_openml(\"mnist_784\", version=1, as_frame=False, return_X_y=True)\nX = X.astype(\"float32\") / 255.0\ny = y.astype(\"int64\")\nX_train, X_test = X[:60_000], X[60_000:]\ny_train, y_test = y[:60_000], y[60_000:]\n\nclf = MLPClassifier(\n    hidden_layer_sizes=(256, 128), activation=\"relu\",\n    solver=\"adam\", batch_size=128, max_iter=20, random_state=0,\n)\nclf.fit(X_train, y_train)\nprint(f\"MNIST test accuracy (sklearn MLP): \"\n      f\"{accuracy_score(y_test, clf.predict(X_test)):.4f}\")\n```\n\n### The same MLP in Python — `PyTorch`\n\nThe same model with explicit autodiff and an explicit training\nloop. This is the PyTorch idiom you'll see everywhere in the deep\nlearning book:\n\n```{.python filename=\"units/unit_02/scripts/mnist_mlp_pytorch.py\"}\n# pip install torch torchvision\nimport torch, torch.nn as nn\nfrom torch.utils.data import DataLoader\nfrom torchvision import datasets, transforms\n\ndevice = \"cuda\" if torch.cuda.is_available() else \"cpu\"\ntf  = transforms.Compose([transforms.ToTensor(), transforms.Lambda(torch.flatten)])\ntr  = datasets.MNIST(\"~/torch-data\", train=True,  download=True, transform=tf)\nte  = datasets.MNIST(\"~/torch-data\", train=False, download=True, transform=tf)\ntl  = DataLoader(tr, batch_size=128, shuffle=True)\nvl  = DataLoader(te, batch_size=512)\n\nmodel = nn.Sequential(\n    nn.Linear(784, 256), nn.ReLU(),\n    nn.Linear(256, 128), nn.ReLU(),\n    nn.Linear(128, 10),\n).to(device)\nopt   = torch.optim.Adam(model.parameters(), lr=1e-3)\nloss  = nn.CrossEntropyLoss()\n\nfor epoch in range(10):                 # mini-batch SGD with Adam\n    model.train()\n    for X, y in tl:\n        X, y = X.to(device), y.to(device)\n        opt.zero_grad()\n        loss(model(X), y).backward()    # backprop\n        opt.step()\n\n    # eval\n    model.eval()\n    correct = total = 0\n    with torch.no_grad():\n        for X, y in vl:\n            X, y = X.to(device), y.to(device)\n            pred = model(X).argmax(dim=1)\n            correct += (pred == y).sum().item()\n            total   += y.size(0)\n    print(f\"epoch {epoch:2d}  test acc = {correct / total:.4f}\")\n```\n\nThe structural beats — `model.train()` / `model.eval()` mode,\n`opt.zero_grad()` to clear accumulated gradients, the inner\n`loss.backward(); opt.step()` two-liner — are PyTorch idiom you'll\nsee in every textbook and tutorial. *Functionally* it's the same\ntraining loop as `mnist_linear_lux.jl` (§2.3). The only ecosystem\ndifference is whether parameters live on the model object (PyTorch)\nor in a separate `ps` tuple (Lux).\n\nRun it via\n[`scripts/mnist_mlp_pytorch.py`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_02/scripts/mnist_mlp_pytorch.py){target=\"_blank\"}\nafter installing torch + torchvision; expect ~30 s/epoch on a\nmodern laptop CPU, much less on GPU.\n\nAll three implementations follow the same skeleton — load data,\ndefine model, set optimiser, loop minibatches, compute loss,\nstep. The Julia version makes the parameter state explicit;\nPyTorch and `scikit-learn` hide it. The only meaningful differences\nare surface-level. Pick by ecosystem.\n\n::: {#ex-2-8 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — parameters, accuracy, and a two-phase finetune\n\nThe unit has now climbed the whole MNIST ladder: random forest (~97%),\nsoftmax regression (~92%), an MLP in Python and in Julia (~98%), and\nthe LeNet CNN above (~98.8%). Two questions about that ladder:\n\n1. **Parameter efficiency.** Use `Lux.parameterlength` to count the\n   parameters of three Julia models: the §2.3 softmax classifier\n   (`784 → 10`), the GPU-section MLP (`784 → 256 → 128 → 10`), and the\n   LeNet CNN. Rank them by accuracy *and* by parameter count — the CNN\n   should come out most accurate while **not** being the largest.\n   Explain in one sentence why a convolution needs so few weights.\n2. **A miniature Adam → L-BFGS schedule.** Re-run `conv_mnist_lux.jl`\n   but, after the 10 `Adam(1f-3)` epochs, do **5 more epochs at a 10×\n   smaller learning rate** (`Adam(1f-4)`). Note the effect on the final\n   test accuracy. That fast-then-careful pattern is a miniature of the\n   **Adam → L-BFGS** schedule every PINN in Units 5–10 uses.\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\n`Lux.parameterlength(model)` counts any model with no hand-arithmetic — build all three the same way: softmax `Lux.Chain(Lux.Dense(784 => 10))`, MLP `Lux.Chain(Lux.Dense(784=>256,relu), Lux.Dense(256=>128,relu), Lux.Dense(128=>10))`, and the CNN via the script's `make_cnn()`. You should get 7,850 / 235,146 / 61,706 — the CNN is most accurate yet under a third of the MLP's weights, because a convolution reuses one small filter at every image position. For the finetune, keep the trained `ps`, rebuild only the optimiser state `opt = Optimisers.setup(Adam(1f-4), ps)`, then run 5 more epochs with the same per-epoch training call the script already defines.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-8)\n:::\n:::\n\n## 2.9 Kolmogorov-Arnold networks (KANs)\n\nA recent alternative to the MLP that's been picking up traction in\nthe PINN community: **Kolmogorov-Arnold networks**\n([Liu et al. 2024](https://arxiv.org/abs/2404.19756){target=\"_blank\"}).\nWhere an MLP puts a fixed activation $\\sigma$ at every node and\nlearns the *weights* on the edges, a KAN puts a *learnable*\nunivariate function (a B-spline) on every edge and just *sums* them\nat the nodes:\n\n$$\n\\underbrace{f_{\\text{MLP}}(x) = W_2\\, \\sigma(W_1 x + b_1) + b_2}_{\\text{fixed }\\sigma\\text{, learnable }W}\n\\qquad\\text{vs.}\\qquad\n\\underbrace{f_{\\text{KAN}}(x)_q = \\sum_p \\phi_{q, p}^{(2)}\\!\\Bigl(\\sum_r \\phi_{p, r}^{(1)}(x_r)\\Bigr)}_{\\text{learnable univariate }\\phi\\text{ on every edge}}.\n$$\n\nThe motivation is the **Kolmogorov-Arnold superposition theorem**\n(1957): any continuous multivariate function on a compact domain\ncan be written as a finite sum of single-variable functions of\nsingle-variable functions — the same universal-approximation\nspirit as MLPs but with a structurally different parameterisation.\nIn practice KANs trade fewer parameters for more interpretability\n(you can plot every edge's learned $\\phi$) at the cost of a more\nexpensive forward pass.\n\nFor PINNs the appeal is that learnable univariate splines often\nneed many fewer collocation points to capture sharp features in\nthe PDE solution. Some preliminary results\n([KAN-PINN](https://arxiv.org/abs/2406.02496){target=\"_blank\"})\nsuggest KANs can outperform MLPs on stiff or oscillatory PDEs —\nthis is an active research front.\n\n### KAN in Julia (`KolmogorovArnold.jl`)\n\nA 2-layer KAN approximating $f(x_1, x_2) = \\exp(\\sin(\\pi x_1) + x_2^2)$\n— a Liu et al. demo — in the Julia ecosystem using\n[`KolmogorovArnold.jl`](https://github.com/vpuri3/KolmogorovArnold.jl){target=\"_blank\"}:\n\n```{.julia filename=\"units/unit_02/scripts/kan_julia.jl\"}\n# Uses KolmogorovArnold.jl (pinned to 0.0.1), which ships in the course @pinn\n# environment — no install needed.\nusing KolmogorovArnold, Lux, Random, Zygote, Optimisers, Statistics\n\nrng = Random.MersenneTwister(0)\n\n# data ─────────────────────────────────────────────────────────────────\nn = 1000\nX = 2f0 .* rand(rng, Float32, 2, n) .- 1f0\ny = reshape(exp.(sinpi.(X[1, :]) .+ X[2, :].^2), 1, n)\n\n# KAN 2 → 5 → 1.  KDense(in, out, grid_len): grid_len = number of RBF basis\n# centres on each edge — the spline resolution (more = a finer learnable φ).\ngrid_len = 6\nmodel = Lux.Chain(\n    KDense(2, 5, grid_len; basis_func = rbf, normalizer = softsign),\n    KDense(5, 1, grid_len; basis_func = rbf, normalizer = softsign),\n)\nps, st = Lux.setup(rng, model)\n\nloss(ps, st) = mean(abs2, first(model(X, ps, st)) .- y)\nopt_state = Optimisers.setup(Optimisers.Adam(1f-2), ps)\nfor k in 1:2000\n    gs = first(Zygote.gradient(p -> loss(p, st), ps))\n    opt_state, ps = Optimisers.update(opt_state, ps, gs)\nend\n@info \"test MSE = $(loss(ps, st))\"\n```\n\n*Setup note.* `KolmogorovArnold.jl` ships in the course `@pinn`\nenvironment (pinned to 0.0.1), so `using KolmogorovArnold` just works —\nno `Pkg.add` needed. The package uses **radial basis functions** as the\nper-edge basis instead of B-splines — a near-equivalent\nparameterisation with better Julia ergonomics. See [The `@pinn` Julia\nenvironment](../pinn_env/pinn_env.qmd#adding-packages).\n\n**What's actually on each edge — the splines and the parameters.** Every edge's\nlearnable function $\\phi$ is a weighted sum of `grid_len` fixed *basis bumps* —\nB-splines in the original Liu et al. paper, **radial basis functions** (smooth\nGaussian-like bumps) in `KolmogorovArnold.jl`. So the three `KDense` arguments are\n`(in_dims, out_dims, grid_len)`: an `in → out` layer has `in × out` edges, and\neach edge carries `grid_len` trainable coefficients — the heights of its bumps —\nso the layer holds roughly `in × out × grid_len` parameters. The `normalizer`\n(here `softsign`) squashes each input into the fixed range the bumps live on, so\none grid covers any input. **Turning `grid_len` up makes every $\\phi$ more\nflexible — it captures sharper features, but adds parameters and slows the forward\npass;** it is the KAN's main capacity knob, the way width and depth are an MLP's.\nThe `2 → 5 → 1` network above has $2{\\times}5 + 5{\\times}1 = 15$ edges at\n`grid_len = 6`, for **105 trainable parameters** — and it fits the demo target to\na test MSE of $\\approx 10^{-3}$. (Contrast the MLP, where each edge holds a single\nweight; a KAN moves the parameters *onto* the edges as little functions.)\n\n![On one KAN edge the basis bumps are **fixed** (left): six smooth Gaussian-like humps spaced across the input range. The edge's learnable function $\\phi$ (right, thick black) is just their **weighted sum** — training only slides the six heights $w_k$ up and down (the faint dashed curves are the scaled bumps that add up to it). Turning `grid_len` up adds more bumps, so $\\phi$ can bend more sharply.](figures/kan_splines.png)\n\nA **spline**, in plain terms, is a curve built from simple *local* pieces instead\nof one global formula. Each bump only matters near its own centre, so changing one\nheight $w_k$ reshapes $\\phi$ *near that bump* and leaves the rest of the curve\nalone. That locality is the whole point: a spline can capture a sharp feature — a\nkink, a steep front — by adjusting a couple of nearby bumps, without disturbing the\nfunction everywhere else. It is exactly the property KANs lean on for PINNs, where\na few well-placed bumps can resolve a steep PDE solution that a single smooth\nglobal activation would smear out. (The original Liu et al. paper uses **B-splines**\n— piecewise-polynomial bumps tied to a grid of *knots*; `KolmogorovArnold.jl` uses\nradial basis functions, which behave the same way for our purposes.)\n\n### KAN in Python (`pykan`)\n\nThe reference Liu-et-al. implementation, in Python:\n\n```{.python filename=\"units/unit_02/scripts/kan_pykan.py\"}\n# pip install pykan\nimport torch\nfrom kan import KAN, create_dataset\n\n# build dataset for f(x1, x2) = exp(sin(pi x1) + x2^2)\nf = lambda x: torch.exp(torch.sin(torch.pi * x[:, [0]]) + x[:, [1]]**2)\ndataset = create_dataset(f, n_var=2, train_num=1000, test_num=1000)\n\n# KAN with grid=5 B-spline knots, k=3 cubic splines, shape 2→5→1\nmodel = KAN(width=[2, 5, 1], grid=5, k=3, seed=0)\nmodel.fit(dataset, opt=\"LBFGS\", steps=50, lamb=0.0)\n\nprint(f\"test loss = {torch.mean((model(dataset['test_input']) - dataset['test_label'])**2).item():.3e}\")\n```\n\nAvailable as\n[`scripts/kan_pykan.py`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_02/scripts/kan_pykan.py){target=\"_blank\"}.\nRequires `pip install pykan` (which pulls in torch). Notice the\ndefault training optimiser is **L-BFGS** — exactly the small-batch\nregime we just discussed.\n\n### When to reach for a KAN\n\nThe honest answer in mid-2026: rarely yet, but worth knowing.\n\n- **Where they shine.** Low-dimensional problems where\n  interpretability matters; PDE solutions with sharp features that\n  an MLP would need many neurons to capture; symbolic-regression\n  applications.\n- **Where they don't.** High-dimensional image-style inputs\n  (CNNs / transformers still dominate); production deep learning\n  (the MLP-Adam-cross-entropy stack is still vastly more debugged).\n- **For PINNs specifically.** A reasonable experimental swap-in\n  for the inner MLP of a PINN — `NeuralPDE.jl` accepts any `Lux`\n  chain, so the substitution is a one-liner. Whether KANs\n  meaningfully improve PINN convergence is still being worked out.\n\nWe won't return to KANs in the worked examples — Units 5–9 stick\nwith MLP-PINNs — but they belong in the working vocabulary of any\npractitioner reading the 2024–26 PINN literature.\n\n::: {#ex-2-9 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — KAN vs MLP on a sharp feature\n\nSharp features are where KANs claim an edge. Fit both a 2-layer\nKAN (`KolmogorovArnold.jl`, as in the script above) and a\nparameter-matched `tanh` MLP to the 1-D function\n$f(x) = |x| + 0.2\\sin(5x)$ on $[-1, 1]$ — smooth everywhere except\nthe kink at zero. Train both with Adam for the same number of\niterations, compare final MSE, and plot both fits near $x = 0$.\nWhich model captures the kink better at equal parameter count, and\nwhat happens to the MLP if you give it 10× the training iterations?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\n`KolmogorovArnold.jl` is already in `@pinn`, so `using KolmogorovArnold` just works. Target: `y = abs.(x) .+ 0.2f0 .* sin.(5f0 .* x)`. KAN: stack two `KDense(in, out, 6; basis_func = rbf, normalizer = softsign)` layers (e.g. `1=>6` then `6=>1`). Parameter-match the MLP with a quick `Lux.parameterlength` check — `Lux.Chain(Lux.Dense(1=>14,tanh), Lux.Dense(14=>14,tanh), Lux.Dense(14=>1))` is close — an unmatched comparison is meaningless. Train both with the same `Adam` loop and iteration count, then zoom the plot into `x ∈ [-0.1, 0.1]`; the global MSE hides where the kink lives. Then give the MLP 10× the iterations and watch it slowly close the gap (an efficiency edge, not an expressiveness one).\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-9)\n:::\n:::\n\n## 2.10 What carries over to PINNs\n\nThree ideas from this unit survive the journey to physics-informed\nnetworks:\n\n1. **Loss minimisation** as the unifying training principle. PINNs\n   add residual terms to the loss but keep the empirical-risk\n   skeleton.\n2. **Generalisation** as the goal. A PINN that fits its collocation\n   points but violates physics elsewhere is *overfitting*; held-out\n   collocation samples play the role of the test set.\n3. **Regularisation by physics**. The PDE residual is a domain\n   prior — a regulariser sharper than any $L_2$ penalty, because\n   it actually encodes what the function *must* satisfy.\n\nWith those in hand, [Unit 3](../unit_03/unit_03.qmd) lifts the\nfunction-approximation idea into a SciML landscape, and\n[Unit 4](../unit_04/unit_04.qmd) introduces the ODE side that PINNs\nwill meet head-on in [Unit 5](../unit_05/unit_05.qmd).\n\n::: {#ex-2-10 .callout-note .section-exercise icon=\"false\" collapse=\"true\"}\n## ✏️ Section exercise — translate the vocabulary\n\nA quick dictionary drill before moving on. For each supervised-learning\nconcept on the left, write down its PINN counterpart and one\nsentence on what changes: (a) a labelled training example; (b) the\ntest set; (c) overfitting; (d) the $L_2$ weight penalty; (e) the\nmini-batch. Then answer: in what sense does a PINN have \"infinite\ntraining data\", and what is the catch?\n\n::: {.exercise-hint tabindex=\"0\"}\n💡 Hint\n\n::: {.exercise-hint-text}\nFor each concept, ask: what supplies the supervision signal in a PINN (the equation), and what plays the role of unseen data (points you didn't sample)? The §2.1 ERM picture maps over almost mechanically — the one genuinely new idea is that the regulariser *is* the physics.\n:::\n:::\n\n::: {.exercise-solution-link}\n[Go to solution →](../exercise_solutions/exercise_solutions.qmd#sol-2-10)\n:::\n:::\n\n",
    "supporting": [
      "unit_02_files"
    ],
    "filters": [],
    "includes": {}
  }
}