#!/usr/bin/env bash
#
# build.sh — render the whole course as ONE PDF booklet, WITHOUT re-running Julia.
#
# Usage:
#   ./booklet/build.sh            build _booklet/…Course-Notes.pdf
#   ./booklet/build.sh --open     build, then open the PDF
#   ./booklet/build.sh --help     show this help
#
# Why it never recomputes Julia
#   Quarto's freeze cache is format-specific: the committed results are
#   `_freeze/**/execute-results/html.json`, but a PDF render looks for
#   `tex.json`. The freeze *hash*, however, is computed from the document
#   SOURCE, not the output format — so copying each html.json into the tex.json
#   slot (and dropping its HTML-only payload) makes `freeze: auto` see a
#   matching hash and reuse it. The PDF render then executes zero code cells and
#   the whole book builds in ~1 minute. (If the html freeze is stale you get
#   stale-but-valid output, never a Julia run.)
#
# Dependencies (see README "PDF booklet" for install commands):
#   quarto, a LaTeX engine with xelatex, rsvg-convert (librsvg), python3,
#   and the JuliaMono font (its glyphs are what let ζ, τ, ∂, λ, T̃ … render
#   inside code blocks).
#
set -euo pipefail

case "${1:-}" in
  -h|--help) sed -n '2,24p' "$0"; exit 0 ;;
esac

cd "$(dirname "$0")/.."   # repo root

say() { printf '\033[1;34m▶\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# ── 1. Preflight: required tools ─────────────────────────────────────────────
need() { command -v "$1" >/dev/null 2>&1 || die "missing '$1' — $2"; }
need quarto       "install Quarto: https://quarto.org/docs/get-started/"
need python3      "install Python 3 (ships with macOS; 'apt install python3' on Linux)"
need xelatex      "install TeX — macOS: 'brew install --cask mactex-no-gui' or 'quarto install tinytex'; Linux: 'apt install texlive-xetex texlive-fonts-recommended'"
need rsvg-convert "install librsvg — macOS: 'brew install librsvg'; Linux: 'apt install librsvg2-bin'"

# ── 2. Locate the JuliaMono font (macOS + Linux dirs) ────────────────────────
say "Locating JuliaMono…"
FONTFILE=""
for d in "$HOME/Library/Fonts" "/Library/Fonts" \
         "$HOME/.fonts" "$HOME/.local/share/fonts" \
         "/usr/share/fonts" "/usr/local/share/fonts"; do
  [ -d "$d" ] || continue
  f=$(find "$d" -name 'JuliaMono-Regular.ttf' 2>/dev/null | head -1)
  [ -n "$f" ] && { FONTFILE="$f"; break; }
done
[ -n "$FONTFILE" ] || die "JuliaMono not found.
  macOS:  brew install --cask font-juliamono
  Linux:  mkdir -p ~/.fonts && cd ~/.fonts &&
          curl -fLO https://github.com/cormullion/juliamono/raw/master/JuliaMono-Regular.ttf &&
          (also -Bold/-RegularItalic/-BoldItalic for full styling) && fc-cache -f"
FONTDIR=$(dirname "$FONTFILE")
say "Using JuliaMono from: $FONTDIR"

# ── 3. Generate the LaTeX font header (only the weights that exist) ───────────
OPTS="Path=$FONTDIR/, Extension=.ttf, UprightFont=*Regular, Scale=0.82"
[ -f "$FONTDIR/JuliaMono-Bold.ttf" ]          && OPTS="$OPTS, BoldFont=*Bold"
[ -f "$FONTDIR/JuliaMono-RegularItalic.ttf" ] && OPTS="$OPTS, ItalicFont=*RegularItalic"
[ -f "$FONTDIR/JuliaMono-BoldItalic.ttf" ]    && OPTS="$OPTS, BoldItalicFont=*BoldItalic"
printf '%% generated by booklet/build.sh — do not edit\n\\setmonofont{JuliaMono-}[\n  %s]\n' "$OPTS" > booklet/header.tex

# ── 3b. Cover credits: which commit this is built from, authorship, license ───
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
CDATE=$(git show -s --format=%cd --date=short HEAD 2>/dev/null || echo "")
DIRTY=""; git diff --quiet 2>/dev/null || DIRTY=" + uncommitted local changes"
REPO="https://github.com/open-AIMS/Julia_PINN_training_2026"
say "Built from commit ${COMMIT}${DIRTY} (${CDATE})"
cat >> booklet/header.tex <<TEX
\publishers{\normalsize
Created by Yoni Nazarathy, Accumulation Point Pty Ltd.\\\\[4pt]
Developed in collaboration with the Australian Institute of Marine Science (AIMS).\\\\
AIMS contact: Dr Takuya Iwanaga.\\\\[8pt]
Built from commit \\texttt{${COMMIT}}${DIRTY} (${CDATE}) of\\\\
\\url{${REPO}}\\\\[4pt]
License and attribution as per that repository.}
TEX

# ── 4. Reuse the HTML freeze for the PDF (no Julia recompute) ─────────────────
say "Reusing HTML freeze for PDF (no Julia recompute)…"
python3 - <<'PY'
import json, glob
n = 0
for hp in glob.glob('_freeze/**/execute-results/html.json', recursive=True):
    tp = hp[:-len('html.json')] + 'tex.json'
    d = json.load(open(hp)); r = d.get('result', {})
    r['includes'] = {}                                          # drop HTML <head>/deps
    if 'preserve' in r:           r['preserve'] = {}            # drop preserved raw HTML
    if 'engineDependencies' in r: r['engineDependencies'] = {}
    json.dump(d, open(tp, 'w')); n += 1
print(f"  synced {n} freeze result(s) html.json -> tex.json")
PY

# ── 5. Render the book ───────────────────────────────────────────────────────
say "Rendering booklet…"
quarto render --profile booklet --to pdf

PDF=$(ls -t _booklet/*.pdf 2>/dev/null | head -1 || true)
[ -n "$PDF" ] || die "render finished but no PDF found in _booklet/"
say "Booklet written to: $PDF"

if [ "${1:-}" = "--open" ]; then
  if   command -v open     >/dev/null 2>&1; then open "$PDF"
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$PDF"
  fi
fi
