{
  "hash": "74bfb61a3b9e4da6c6b442a15faea7b8",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"Project Solution\"\nengine: julia\ntoc-title: \"Project Solution\"\ndate: today\ndate-format: \"DD/MM/YYYY\"\n---\n\n```{=html}\n<style>\n  .solution-gate {\n    margin: 1.5em 0;\n    border: 2px solid #caa436;\n    border-radius: 6px;\n    background: #fffbe6;\n    overflow: hidden;\n  }\n  .solution-gate-bar {\n    padding: 1em 1.4em;\n    background: #ffe066;\n    color: #20242c;\n    cursor: pointer;\n    user-select: none;\n    display: flex;\n    align-items: center;\n    justify-content: space-between;\n    font-weight: bold;\n    font-size: 1.05em;\n  }\n  .solution-gate-bar .tally {\n    font-family: ui-monospace, Menlo, monospace;\n    font-size: 0.9em;\n    background: #20242c;\n    color: #ffe066;\n    padding: 0.15em 0.6em;\n    border-radius: 3px;\n  }\n  .solution-gate-body {\n    display: none;\n    padding: 1em 1.4em;\n  }\n  .solution-gate.unlocked .solution-gate-bar {\n    background: #d8f0c8;\n    color: #1a4a1a;\n    cursor: default;\n  }\n  .solution-gate.unlocked .solution-gate-bar .tally {\n    background: #1a4a1a;\n    color: #d8f0c8;\n  }\n  .solution-gate.unlocked .solution-gate-body {\n    display: block;\n  }\n</style>\n\n<script>\n(function() {\n  window.solutionGateClick = function(id) {\n    const gate = document.getElementById(id);\n    if (!gate || gate.classList.contains(\"unlocked\")) return;\n    const now = Date.now();\n    let n = parseInt(gate.dataset.clicks || \"0\", 10);\n    const first = parseInt(gate.dataset.firstClickAt || \"0\", 10);\n    if (now - first > 1200) {\n      n = 0;\n      gate.dataset.firstClickAt = String(now);\n    }\n    n += 1;\n    gate.dataset.clicks = String(n);\n    gate.querySelector(\".tally\").textContent = n + \" / 3 clicks\";\n    if (n >= 3) {\n      gate.classList.add(\"unlocked\");\n      gate.querySelector(\".tally\").textContent = \"unlocked\";\n    }\n  };\n})();\n</script>\n```\n\nThis unit is the worked **solution** to the capstone spec laid out\nin [Unit 9](../unit_09/unit_09.qmd). The science behind the model\nsits in [Unit 8](../unit_08/unit_08.qmd). Here we cover three\nthings in this order:\n\n- **Shared infrastructure** (§10.1 — open). The finite-difference\n  reference solver, the toy-task ladder ([Unit 9 §9.11](../unit_09/unit_09.qmd#sec-toy-tasks)),\n  and the SWE driver. Both Task A and Task B start from these.\n- **Solution to Task A** (§10.2 — *locked, triple-click to unlock*).\n  Single-site CPU-friendly inverse problem.\n- **Solution to Task B** (§10.3 — *locked, triple-click to unlock*).\n  Three-site joint inverse with the modern PINN toolkit, plus the\n  sub-scale CPU prototype steps.\n\nEach solution sits behind its own triple-click gate, so you can\nread the shared infrastructure (and one task's solution, if you\nwant) without spoiling the other. We strongly recommend you\n**attempt each task yourself first** — the learning is in working\nthrough the inverse problem, not in reading our answer.\n\n## 10.1 Shared infrastructure: the forward solver and scenarios {#sec-shared}\n\nBefore either solution, here are the building blocks both tasks rely on:\nthe finite-difference **forward solver** (the ground-truth $T(z,t)$ the\nPINNs are scored against — and the thing that generates the mooring data),\nthe five **toy scenarios** of\n[Unit 9 §9.11](../unit_09/unit_09.qmd#sec-toy-tasks), and the SWE driver.\n\nThis section is deliberately **not** behind a solution gate like §10.2–§10.3:\nit is shared setup you need to *start* either task, not the answer to one.\nThe gated sections below are the actual inverse solutions.\n\nThe five scenarios here **are** the\n[§9.11 toy-task ladder](../unit_09/unit_09.qmd#sec-toy-tasks), in the same\norder and numbering — §9.11 *describes* each step and what mechanism it\nisolates; this section *works* it with the solver and shows the figure.\nEach one just switches on one more term of the column PDE:\n\n| # | §9.11 ladder step | what it adds |\n|---|---|---|\n| 1 | pure diffusion, steady forcing | $\\kappa\\,\\partial_{zz}T$ only → linear steady profile |\n| 2 | + diurnal cycle | time-varying $Q_{\\text{SW}}(t)$ + body source |\n| 3 | + upwelling | advection $w\\,\\partial_z T$ (κ stays constant) |\n| 4 | + storm gust (prescribed) | a Gaussian storm modulating $w$ and cloud |\n| 5 | + SWE-driven storm | $w(t)$ from a shallow-water solve (the design, §10.5) |\n\nScenarios 1–4 ship with worked figures below; scenario 5 (the full SWE\ndriver) is the design for the headline extension (§10.5), not shipped\nwith the solution.\n\n### Finite-difference reference solver\n\nA method-of-lines finite-difference reference for $T(z, t)$ — the\nground truth we compare PINN predictions against. Uses\n`MethodOfLines.jl` with adaptive time-stepping; second-order\ncentral differences in $z$, with the surface Neumann condition\nimposed via a ghost cell. The full source listing is in §10.6;\nbelow we work through scenarios 1–4 of the\n[Unit 9 §9.11](../unit_09/unit_09.qmd#sec-toy-tasks) ladder (scenario 5,\nthe SWE driver, follows as the design).\n\nThese four scenario plots all run on the **generic reference column**\n(the §9.6 reference parameters, $H = 100$ m) so each mechanism shows\ncleanly in isolation — they are **not** the per-site mooring records\n(Sites A/B/C). Those site records are produced separately, each at its\nown depth, by `generate_mooring_csvs.jl` (which runs this same solver\nthrough the scenario-4 storm per site).\n\n#### Scenario 1 — pure diffusion to steady state (§9.11 step 1)\n\n$w = 0$, $\\mathcal{S} = 0$, $\\kappa$ constant, $Q_{\\text{np}}$\nconstant. After ~365 days the column reaches a near-steady state.\n\n![Scenario 1 — pure diffusion to a (near-)steady state, from `scenario_1()` in `scripts/column_fd.jl`. The grey **IC** is the initial $\\tanh$ thermocline: a warm (~28 °C) mixed layer over an 18 °C deep reservoir, with the sharp transition near $z=-30$ m. With no advection, no source, and a constant surface cooling $Q_{\\text{np}}=-200$ W/m², diffusion erases that thermocline and the column relaxes toward the **straight-line** steady profile — heat conducts up the gradient from the fixed deep reservoir to be lost at the surface, so the surface ends up *colder* (~13 °C) than the deep (18 °C). The blue **MOL final** curve is the finite-difference solution after ~365 days; the dashed black **analytic** line $T(z)=T_{\\text{deep}}-\\tfrac{Q_{\\text{cool}}}{\\kappa_m \\rho_0 c_p}(z+H)$ is drawn on top of it. The two are indistinguishable — they agree to $\\approx 4\\times10^{-3}$ °C, so the dashes ride directly along the blue line, and *that overlap is the validation* of the solver. The analytic line is $T(z)=T_{\\text{deep}}+\\tfrac{Q_{\\text{np}}}{\\rho_0 c_p\\kappa_m}(z+H)$ — steady, no advection or source, so $\\partial_z(\\kappa\\partial_z T)=0$ gives a straight line whose slope the surface flux sets and whose intercept the deep reservoir pins.](output/scn1_steady.png)\n\n#### Scenario 2 — diurnal cycle (§9.11 step 2)\n\nAdds $Q_{\\text{SW}}(t)$ (smooth half-cosine, mean 400 W/m²) and the\nBeer–Lambert body source $\\mathcal{S}$.\n\n![Scenario 2 output — near-surface traces (top) make the daily warm/cool cycle plain: ten diurnal oscillations ride on the slow relaxation toward the scenario-1 steady state, with the amplitude largest at $z=-1$ m and damped by $z=-7$ m. The top-10 m $(z,t)$ heatmap (bottom) shows the same field.](output/scn2_diurnal.png)\n\n#### Scenario 3 — upwelling (§9.11 step 3)\n\nAdds an upwelling profile $w(z) = w_0 \\sin(\\pi(z+H)/H)$ with\n$w_0 = 10^{-5}\\,\\text{m/s}$. (This toy scenario uses a $\\sin$ shape to\nshow the mechanism cleanly on the generic column; the capstone's own $w$\nis the linear-in-$z$ profile derived in\n[Unit 9 §9.2](../unit_09/unit_09.qmd#sec-w-coupling).)\n\n![Scenario 3 output — five-mooring traces (top) and full $(z, t)$ heatmap (bottom). SST drops 28 → 22 °C; mid-column warms via diffusion (Pe ≈ 1).](output/upwelling_mooring.png)\n\n#### Scenario 4 — storm fingerprint (prescribed gust) (§9.11 step 4)\n\nGaussian gust at $t_{\\text{storm}} = 10$ days, $\\sigma = 1$ day,\nmodulating both $w_0$ (×5 at peak) and $Q_{\\text{SW}}^{\\max}$ (×0.5\nat peak via cloud cover). Real SWE-driven forcings will replace\nthese envelopes in scenario 5 (the synthetic scenario, forward).\n\n![Scenario 4 output — `scenario_4()` uses prescribed Gaussian envelopes for the gust-driven upwelling and cloud cover, pending the SWE driver. The storm bump is visible around day 10.](output/storm_fingerprint_mooring.png)\n\n### Shallow-water driver (scenario-5 forcing — the design)\n\nThe shipped column scripts use the *prescribed* Gaussian\nupwelling/cloud envelopes of toy scenario 4 (above). The natural\nnext step — **scenario 5** — replaces those hand-drawn envelopes\nwith a physically self-consistent horizontal current from a\nshallow-water solve. We describe that bridge here as the design;\nwiring it into the column model is the headline extension in\n[§10.5](#sec-where-to-go) rather than something the capstone\nsolution ships.\n\nThe driver would be a staggered-grid finite-volume SWE reference\non a 100 × 100 km patch of the central GBR shelf, with constant\nbackground depth $H = 80\\,\\text{m}$, the local Coriolis parameter\n$f = 2\\Omega\\sin(-19°) \\approx -4.7 \\times 10^{-5}\\,\\text{s}^{-1}$,\nand a spatially-Gaussian wind-stress patch driving the storm:\n\n$$\n\\tau(x, y, t) \\;=\\;\n\\tau_0(t)\\,\\exp\\!\\left[-\\,\\frac{(x - x_0)^2 + (y - y_0)^2}{2\\,L_\\tau^2}\\right],\n$$\n\nwith $L_\\tau = 30\\,\\text{km}$, $(x_0, y_0)$ tracking a slow-moving\ngust centre (10 km/h drift over 3 days), and $\\tau_0(t)$ the\nGaussian-envelope time profile that **becomes the unknown** in\nthe inverse problem.\n\nWhat would get piped to the column model: $\\mathbf{u}_h(t)$ at each\nof the three mooring locations, from which $w(z, t) = -(z + H)\\,\n\\nabla_h\\cdot \\mathbf{u}_h(t)$ (incompressibility + linear-in-$z$\nansatz from [Unit 9 §9.2](../unit_09/unit_09.qmd)) gives the\ncolumn's vertical advection. This is what replaces the prescribed\nGaussian $w_0(t)$ of toy scenario 4 with a physically\nself-consistent $w(t)$ that carries the Coriolis turning of the\nwind-driven current, the propagation delay from gust centre to each\nmooring, and the geometric spreading that makes Site C see a smaller\n$w_{\\max}$ than Site A despite being further from coast — exactly the\ninter-site contrast the joint inverse (§10.3) leans on. The same\nlinearised shallow-water machinery is already worked end-to-end in\n[Unit 1](../unit_01/unit_01.qmd), which is the cleanest starting\npoint if you build it.\n\n## 10.2 Solution to Task A\n\n```{=html}\n<div class=\"solution-gate\" id=\"gate-task-a\">\n  <div class=\"solution-gate-bar\" onclick=\"solutionGateClick('gate-task-a')\">\n    <span>🔒 Solution to Task A — triple-click to reveal</span>\n    <span class=\"tally\">0 / 3 clicks</span>\n  </div>\n  <div class=\"solution-gate-body\">\n```\n\n*Spec: [Unit 9 §9.9](../unit_09/unit_09.qmd#sec-task-a). Site B (Davies\nReef, $H = 60$ m, advection + diffusion), one driver to recover.*\n\nThe solution is a single script,\n[`task_a_inverse_pinn.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_a_inverse_pinn.jl){target=\"_blank\"}\n(~230 lines, on the [Unit 5 §5.3](../unit_05/unit_05.qmd) Lux + Zygote +\nOptimisers skeleton). It synthesises the mooring data from a\nfinite-difference reference solve of the column PDE with a *known* storm\n$\\tau^*(t)$, samples five sensor depths hourly and adds noise, then trains a\nPINN to recover $\\tau(t)$ from those noisy traces — so the recovery error\n$\\hat\\tau$ vs $\\tau^*$ is a real number we can score.\n\nThis is a self-contained **twin experiment**: the script does *not* read\nthe committed `mooring_*.csv` (those are the \"look at realistic data\"\nartifact of [§9.1](../unit_09/unit_09.qmd)) — it plants its own\n$\\tau^\\star$ and recovers it, so the truth is known. For self-containment\nit hand-codes the finite-difference forward solve rather than calling\n`MethodOfLines.jl`; the column model (same $w(z)$, $\\kappa$, $S$) is the\none the inverse uses, so forward and inverse stay consistent.\n\nSo the script reads as two clearly-marked parts. **Part 1 — generate the\ntwin's data:** plant a known $\\tau^\\star$, forward-solve, sample the\nsensors, add noise. This is *test-data generation*, not the answer — it\nlooks like it lives \"inside the solution,\" and it does, on purpose.\n**Part 2 — the inverse PINN:** it sees only that noisy data and recovers\n$\\hat\\tau$; the planted $\\tau^\\star$ is used at the very end *only* to\nscore the result. Generating the data in-file is exactly what makes the\nerror measurable: with a real mooring you would not know $\\tau^\\star$, so\nyou could never report a \"9.6% recovery error.\" This is the standard way\nto validate an inverse method before trusting it on real data.\n\n### Step 1 — The problem: source recovery\n\nThe storm modulates the column's heating: a *known* surface-weighted\nvertical shape $S(\\zeta)$ (Beer–Lambert-like) times an *unknown* time signal\n$\\tau(t)$. Non-dimensionalising the column — temperature\n$\\tilde T = (T-T_\\text{deep})/\\Delta T$ (with $\\Delta T$ the fixed\nsurface-to-deep temperature scale, $\\approx 3\\,°$C at Site B; this is a\n*temperature* scale, not a timestep $\\Delta t$), depth $\\zeta = (z+H)/H$,\nand time $\\tau_t = t/T_f$ — gives\n\n$$\n\\partial_{\\tau}\\tilde T = -W_\\text{adv}\\,w(\\zeta)\\,\\partial_\\zeta\\tilde T + \\mathrm{Pe}\\,\\partial_{\\zeta\\zeta}\\tilde T + S(\\zeta)\\,\\tau(t),\n\\quad \\tilde T(0,\\tau)=0,\\ \\ \\partial_\\zeta\\tilde T(1,\\tau)=0,\\ \\ \\tilde T(\\zeta,0)=0,\n$$\n\nwith the upwelling shape $w(\\zeta)=\\zeta$ (zero at depth, maximal at the\nsurface). The unknown is the scalar-in-time forcing $\\tau(t)$ (one storm\nbump); $S(\\zeta)$, Pe, $W_\\text{adv}$ and the BCs are given. (Two roles\nfor $\\tau$ to keep straight: as a derivative or subscript —\n$\\partial_\\tau$, $\\tau_t = t/T_f$ — it is non-dimensional *time*; the\nstandalone $\\tau(t)$ is the storm *forcing*, the unknown we recover.\nAnd the coefficient here written $\\mathrm{Pe}$ is the normalised\n*diffusion* term, $=1$; the actual Péclet number is\n$W_\\text{adv}\\approx1.2$ — see §9.6.) This\n**source-recovery** form is the most *identifiable* inverse: the source\nover-determines $\\tau(t)$ across all depths at each instant, and a\n$\\tau\\equiv0$ field cannot fit source-driven data — so the network can't\nhide the forcing inside the temperature field (the failure mode a\n*mixing-* or *coefficient*-recovery setup hits when the column sits near\nsteady state). Two networks:\n\n- $\\tilde T_\\theta(\\zeta,\\tau)$ — the temperature field (weights $\\theta$),\n  with the hard IC and deep\n  BC baked into the ansatz $\\tilde T = \\zeta\\,\\tau\\,N_\\theta(\\zeta,\\tau)$, so\n  $\\tilde T(\\zeta,0)=0$ and $\\tilde T(0,\\tau)=0$ hold for free\n  ([Unit 7 §7.3](../unit_07/unit_07.qmd)). The insulating surface flux\n  $\\partial_\\zeta\\tilde T(1,\\tau)=0$ stays a soft penalty.\n- $\\tau_\\phi(\\tau)$ — a small MLP for the storm envelope (signed).\n\nDerivatives use the finite-difference-in-input stencil (no nested AD,\n[Unit 5 §5.3](../unit_05/unit_05.qmd)), so a single reverse-mode pass\nkeeps each training step cheap — cheap enough that the whole inverse\ntrains on a CPU.\n\n### Step 2 — The loss, and the lesson it teaches\n\n$$\n\\mathcal{L}(\\theta,\\phi) =\n\\underbrace{\\lambda_r\\,\\mathcal{L}_\\text{PDE}}_{\\lambda_r=1}\n+ \\underbrace{\\lambda_d\\,\\tfrac{1}{N_d}\\!\\sum_k|\\tilde T_\\theta(\\zeta_k,\\tau_k)-\\tilde T_\\text{obs}|^2}_{\\lambda_d=6000}\n+ \\underbrace{\\lambda_b\\,\\mathcal{L}_\\text{surf-BC}}_{\\lambda_b=10}\n+ \\underbrace{\\lambda_\\text{reg}\\!\\int_0^1|\\tau_\\phi'|^2}_{\\lambda_\\text{reg}=10^{-5}}.\n$$\n\nThe recovered forcing $\\tau_\\phi$ enters **only** the PDE residual, so it\nregresses to $(\\partial_\\tau\\tilde T + W_\\text{adv}\\,w\\,\\partial_\\zeta\\tilde T - \\mathrm{Pe}\\,\\partial_{\\zeta\\zeta}\\tilde T)/S$\n— it is driven by *derivatives* of the temperature field. Here is the\ntrap: the column low-pass-filters $\\tau$ (response time ≈ storm width), so a\nnetwork can match the noisy data *in value* with a too-smooth $\\tilde T$ whose\nderivatives — and hence the recovered storm peak — collapse well below\ntruth. **The cure is not fancier collocation; it is the loss weights.** A\nlarge data weight $\\lambda_d$ forces $\\tilde T$ to honour the sharp data, which\nkeeps its derivatives sharp and lifts the recovered peak; the tiny $H^1$\nweight $\\lambda_\\text{reg}$ only removes single-hour-sample ringing. A weight\nsweep makes the effect concrete:\n\n| $\\lambda_d$ | $\\lambda_\\text{reg}$ | Recovered peak | Comment |\n|---|---|---|---|\n| 100 | $10^{-2}$ | 8% of truth (92% err) | too-smooth $\\tilde T$; storm collapses |\n| 500 | $10^{-4}$ | 56% | sharper, but data weight still too low |\n| 2000 | $3\\times10^{-5}$ | 78% | approaching the floor |\n| **6000** | $10^{-5}$ | **90% (9.6% err)** | the chosen operating point |\n\nAt this sensor noise (storm SNR ≈ 29), ~10% peak error is close to the\n*deconvolution floor*: pushing $\\lambda_d$ harder buys little and starts\nre-introducing ringing. The remaining gap to truth is the inverse-problem\nreality at this noise level, not a tuning failure.\n\n### Step 3 — Results\n\nThe operating point trains a 32-wide × 4-deep field network for 12 000\nAdam steps — **about four minutes on a CPU**. Measured recovery:\n\n- **Peak-amplitude error 9.6%** — comfortably inside the\n  [§9.9.3 criterion](../unit_09/unit_09.qmd#sec-task-a) of $\\leq 15\\%$.\n- **Storm-day timing exact** (well under the 2-hour bar).\n- **Forward field** — reconstructed as $T = T_\\text{deep} + \\Delta T\\,\\tilde T_\\theta$,\n  it matches the FD reference to $\\|T - T_\\text{FD}\\|_{L^2} = 0.002\\,°\\text{C}$,\n  far below the $0.015\\,°\\text{C}$ sensor noise the twin injects.\n- **Whole-envelope relative $L^2$ ≈ 0.09**, with the rising edge slightly\n  smoothed and the tail over-relaxed by a few percent — the classic\n  Tikhonov pull toward zero, the cost of the $H^1$ regulariser.\n\nSite B clears the bar on a CPU because its 60 m column with upwelling\ncarries a sharp, depth-structured storm fingerprint (the sensor fits\nbelow): the surface sensor swings ~0.15 nondim while the deep sensors lag\nand damp, so a single mooring already over-determines $\\tau(t)$. The\nshallower diffusion-only site washes that structure out — which is exactly\nwhy it is the *harder*, less informative inverse, and is kept only as the\n\"easy site\" contrast in the Task B joint study (§10.3). No GPU is\nneeded for Task A; a GPU only lets you widen the network or iterate faster.\n\n![Recovered storm forcing $\\hat\\tau(t)$ vs truth (left) and the five-sensor temperature fits over the noisy data (right), from `task_a_inverse_pinn.jl` on Site B. Peak error 9.6%, storm day exact, forward field within 0.002 °C of the FD reference — all on a CPU in about four minutes.](output/task_a_inverse.png)\n\n### Forward sanity check (shipped)\n\nBefore debugging an inverse on top of a possibly-broken forward, certify the\nforward solve.\n[`column_pinn_gpu.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/column_pinn_gpu.jl){target=\"_blank\"}\ndoes exactly this on the column's pure-diffusion relaxation, where a\nsingle-eigenmode initial condition has an **exact closed-form** solution\n$\\tilde T^*(\\zeta,\\tau) = g\\,\\zeta + A\\sin(\\tfrac{\\pi}{2}\\zeta)\\,e^{-\\mathrm{Pe}(\\pi/2)^2\\tau}$\nto score against. Measured: the CPU sub-scale fit reaches\n$\\|\\tilde T_\\theta-\\tilde T^*\\|_{L^2} = 6\\times10^{-4}$, the A10G full-scale run\n(30× the collocation, ~85× the throughput) $2\\times10^{-3}$ — both far inside\nany noise scale, confirming the field operator and the FD-in-input derivative\nstencil before any inversion.\n\n### Optional extensions (not shipped as code)\n\nThe inverse script plus that forward check answer §9.9. To go further, these are\ngood exercises — they don't ship here:\n\n- **Mechanism partition (the §9.1 question).** The recovered $\\hat\\tau(t)$\n  gives the storm's strength and timing, not *which* physical mechanism\n  dominated the cooling. Re-running the forward solver with $\\hat\\tau$ and\n  accumulating the advection / mixing / surface-flux contributions to\n  $\\Delta T(z=-30\\,\\text{m})$ would partition this site's response — but the\n  *interesting* result is the contrast across regimes, which needs Task B's\n  three sites (§10.3), not one column.\n- **Diagnostics.** Residual-vs-time histograms (a causality check,\n  [Unit 7 §7.5](../unit_07/unit_07.qmd)), heat-budget closure at each sensor\n  depth, and cross-validation on a held-out 24-hour window.\n\n### Files\n\n- [`scripts/task_a_inverse_pinn.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_a_inverse_pinn.jl){target=\"_blank\"} — source-recovery inverse PINN: FD reference solve, synthetic mooring data, joint $\\tilde T_\\theta + \\tau_\\phi$ training; clears the §9.9.3 targets on a CPU in about four minutes.\n- [`scripts/column_pinn_gpu.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/column_pinn_gpu.jl){target=\"_blank\"} — forward sanity check: pure-diffusion forward PINN scored against the closed-form solution, CPU sub-scale + A10G full-scale.\n- [`scripts/column_fd.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/column_fd.jl){target=\"_blank\"} — the finite-difference column solver used as the forward reference.\n\n\n```{=html}\n  </div>\n</div>\n```\n\n## 10.3 Solution to Task B\n\n```{=html}\n<div class=\"solution-gate\" id=\"gate-task-b\">\n  <div class=\"solution-gate-bar\" onclick=\"solutionGateClick('gate-task-b')\">\n    <span>🔒 Solution to Task B — triple-click to reveal</span>\n    <span class=\"tally\">0 / 3 clicks</span>\n  </div>\n  <div class=\"solution-gate-body\">\n```\n\n*Spec: [Unit 9 §9.10](../unit_09/unit_09.qmd#sec-task-b). Three moorings\njointly, $H = 100$ m, modern PINN toolkit, GPU at full scale.\nHere we develop on CPU and queue the GPU launch.*\n\nThe Task A recipe — a single small MLP with hand-tuned weights —\nbreaks at Task B's scale for three concrete reasons:\n\n1. The deep ($H = 100$ m) column has a much wider range of\n   temporal scales (diurnal at the surface, 30-day at depth),\n   so the smooth-MLP ansatz can't fit the high-frequency surface\n   signal *and* the slow deep relaxation simultaneously.\n2. The three-site joint loss has six per-site loss components\n   whose magnitudes differ by 2–3 orders of magnitude — hand\n   tuning isn't feasible.\n3. Forward-over-forward second derivatives at $N_r = 50\\,000$\n   collocation points per site are CPU-bound and stall L-BFGS.\n\nThe four modern-PINN fixes from\n[Unit 7 §7.3](../unit_07/unit_07.qmd) each address one of these\nfailure modes, in the same order: Fourier features (1), adaptive\nloss weighting (2), causal training (1 again, time direction),\nand GPU vectorisation (3).\n\n### Step 1 — The field network and the modern-PINN toolkit\n\n- **Network:** 6-layer MLP, 64 neurons / layer, $\\tanh$.\n- **Fourier feature embedding** at the input:\n  $\\gamma(z, t) = [\\sin(B\\,(z, t)), \\cos(B\\,(z, t))]$ with\n  $B \\sim \\mathcal{N}(0, \\sigma_B^2 I)$ — two banks, $\\sigma_B$\n  tuned per band (one for the diurnal cycle $\\sim 1/86400\\,\\text{s}$,\n  one for the storm envelope $\\sim 1/(3 \\times 86400)\\,\\text{s}$).\n  This breaks the MLP's spectral bias\n  ([Tancik et al. 2020](../references/references.qmd#ref-tancik2020){target=\"_blank\"}).\n- **Hard BC at $z = -H$** as in Task A; **hard IC**:\n  $T_\\theta(z, t) = T_0(z) + t\\,N_\\theta(z, t)$ so the IC loss\n  term drops out entirely. Now only the residual + surface-flux\n  BC + data loss compete for the optimiser's attention.\n- **Adaptive loss weighting** ([McClenny & Braga-Neto 2022](../references/references.qmd#ref-mcclenny2022){target=\"_blank\"})\n  — gradient-balancing recipe:\n  $\\lambda_{\\text{term}}^{(k+1)} \\leftarrow (1 - \\alpha)\\,\\lambda_{\\text{term}}^{(k)} + \\alpha\\,\\frac{\\max\\|\\nabla \\mathcal{L}_{\\text{residual}}\\|_\\infty}{\\overline{\\|\\nabla \\mathcal{L}_{\\text{term}}\\|}_2}$\n  with $\\alpha = 0.1$ updated every 100 iterations.\n- **Causal training** ([Wang et al. 2022](../references/references.qmd#ref-wang2022causal){target=\"_blank\"})\n  — temporal weight $\\omega(t_i) = \\exp(-\\epsilon\\,\\sum_{j<i}\\!r^2(z_j, t_j))$\n  so a $t_i$ collocation only contributes after the\n  $t_{<i}$ residual has converged.\n\nThis is the *menu* the literature offers for the deep multi-scale\ncolumn. The shipped solution is deliberately more conservative: both\nthe sub-scale prototype and the GPU full-scale inverse below use hard\nIC/deep BC + the proven static-weight recipe (Step 2), which is what\nconverges cleanly at this scale. Fourier features earn their keep once\nthe column is deep enough to carry genuinely separated time-scales;\nadaptive weighting and causal training are the next layer the inverse\ncan lean on — Step 6's open questions flag where causal still needs\ncare. We flag the menu so you know what to reach for, not because all\nfour are needed to clear the §9.10 bar.\n\n### Step 2 — Joint three-site inverse\n\nThree column networks $T^{(i)}_\\theta(z, t)$, $i \\in \\{A, B, C\\}$,\neach with the architecture above and *separate* parameters.\n**Shared:** a single 3-layer × 48-neuron MLP $\\tau_\\phi(t)$ for\nthe storm wind-stress envelope all three sites feel.\n\n**Joint loss:**\n\n$$\n\\mathcal{L} \\;=\\;\n\\sum_{i \\in \\{A, B, C\\}}\\!\\!\\Bigl[\n   \\lambda^{(i)}_r\\,\\mathcal{L}^{(i)}_{\\text{PDE}}\n + \\lambda^{(i)}_d\\,\\mathcal{L}^{(i)}_{\\text{data}}\n + \\lambda^{(i)}_b\\,\\mathcal{L}^{(i)}_{\\text{BC}}\n\\Bigr]\n\\;+\\; \\lambda_{\\text{reg}}\\,\\int |\\tau_\\phi'(t)|^2\\, dt.\n$$\n\nThe site-specific weights $\\lambda^{(i)}_{r,d,b}$ matter because the\nthree regimes (Péclet $\\ll 1$, $\\sim 1$, $\\gg 1$) produce residual /\ndata scales that differ across sites. The literature *learns* them by\ngradient-balancing; in practice, at the scale we run, the **proven\nstatic recipe from Task A** — a large data weight $\\lambda_d = 6000$,\na tiny $H^1$ smoothing $\\lambda_\\text{reg} = 10^{-5}$, and hard IC +\ndeep BC — is what converges cleanly, and is what\n[`task_b_joint_inverse.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_b_joint_inverse.jl){target=\"_blank\"}\nships. (A naively-tuned adaptive scheme can *run away* on this\ndeconvolution — over-weighting the noisy data until the recovered\n$\\tau$ blows up; gradient-balancing is the right next step only once\nthe static baseline is trustworthy.)\n\nWhy the shared $\\tau_\\phi$ matters: each site contributes a\n*different observable consequence* of the same physical stress.\nDiffusion-only Site A constrains the storm *amplitude* through the\nmixing response; advection-dominated Site C sees the *shape* of the\ndeep upwelling pulse; Site B sits between. The single shared\n$\\tau_\\phi$ must satisfy all three at once — and that joint constraint\nis what cuts the recovered-peak error from **~20% (Site A alone)** or\n**~12% (Site C alone)** down to **~7% jointly**, measured on the GPU\nfull-scale run (Step 6).\n\n### Step 3 — CPU sub-scale prototype (what we actually run here)\n\nThe full 3-site $H = 100$ m / $N_r = 50\\,000$ launch is GPU-class.\nWithout one,\n[`task_b_subscale_prototype.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_b_subscale_prototype.jl){target=\"_blank\"}\nruns the **two-site joint inverse** at CPU sub-scale: Site A\n(15 m, diffusion-only) and Site B (60 m, advection + diffusion)\nsharing **one** storm envelope $\\tau(t)$. It deliberately uses the\n*same proven static-weight recipe as Task A* — large data weight\n$\\lambda_d = 6000$, tiny $H^1$ smoothing $\\lambda_\\text{reg} = 10^{-5}$,\nhard IC + hard deep BC baked into $\\tilde T = \\zeta\\,\\tau\\,N$, and the\nFD-in-input derivative stencil — extended minimally to two sites\nwith a single shared $\\tau$-network. (The GPU full-scale run in\nStep 6 uses the *same* static recipe at three sites and a wider\nnetwork — the Fourier / adaptive / causal machinery of Step 1 is the\nmenu you reach for when the deep $H=100$ m column forces genuinely\nseparated time-scales, not something this problem needs to clear the\nbar.) It performs three inversions — each ~4–7 min on a CPU at\n12 000 Adam steps, $N_r = 4\\,000$ per site:\n\n1. **Site A alone** — peak-amplitude error **~16%**.\n2. **Site B alone** — **~11%**. Site B's deeper, advection-sharpened\n   thermocline carries more storm information than Cleveland Bay's\n   shallow diffusion-only column, so it recovers the envelope better\n   on its own.\n3. **Joint A + B** — **~7%**, with the storm day recovered exactly.\n   The shared $\\tau(t)$ must satisfy *both* columns at once, so the\n   cross-site constraint cuts the peak error below either single\n   site. **This is the headline finding** — and it is a real,\n   reproducible measurement, not an extrapolation.\n\nA one-page GPU-launch checklist (the deltas for the full 3-site run)\nis in *Files* below.\n\n### Step 4 — Recovered $\\tau(t)$ from the two-site CPU prototype\n\nThe two-site joint inversion produces a $\\hat\\tau(t)$ measurably\nsharper than either single-site recovery:\n\n![Recovered storm envelope $\\hat\\tau(t)$ from `task_b_subscale_prototype.jl`. Either mooring alone under- or over-shoots the peak (Site A ~16%, Site B ~11%); the joint inversion with one shared $\\tau(t)$ tracks the truth to ~7% and locks the storm day exactly.](output/task_b_subscale_recovery.png)\n\n| Feature | Site A alone ($H{=}15$m) | Site B alone ($H{=}60$m) | Joint A+B |\n|---|---|---|---|\n| Peak-amplitude error | ~16% | ~11% | **~7%** |\n| Storm-day timing | exact | exact | **exact** |\n| Whole-envelope rel. $L^2$ | ~0.14 | ~0.10 | **~0.07** |\n\nSite B's stronger thermocline signature dominates the storm-day\namplitude constraint; Site A pins the quieter shoulders of the\nenvelope. Removing either site sends the joint error back up — the\ntwo moorings genuinely constrain different parts of the same signal.\n\n### Step 5 — Mechanism partition across the three sites {#sec-mechanism-partition}\n\nThe §9.1 multi-site story made quantitative. For the *toy* nondim\ncolumn the three right-hand-side terms — vertical advection\n$-W_\\text{adv}\\,w(\\zeta)\\,\\partial_\\zeta\\tilde T$, vertical mixing\n$\\mathrm{Pe}\\,\\partial_{\\zeta\\zeta}\\tilde T$, and the storm source\n$S(\\zeta)\\,\\tau(t)$ — *are* the mechanisms. Integrating each term's\nmagnitude over the storm window at each site's diagnostic depth (from\nthe FD reference, computed in `task_b_joint_inverse.jl`) gives a real\npartition:\n\n| Site | Depth | Péclet $W_\\text{adv}/\\mathrm{Pe}$ | Advection | Mixing | Storm source |\n|---|---|---|---|---|---|\n| A — Cleveland Bay | $z = -10\\,\\text{m}$ | $0$ | 0% | 39% | 61% |\n| B — Davies Reef | $z = -30\\,\\text{m}$ | $\\sim 1.2$ | 15% | 20% | 65% |\n| C — Myrmidon Reef | $z = -50\\,\\text{m}$ | $\\sim 4$ | 27% | 20% | 53% |\n\nThe headline is the **trend**, and it is real: the advection share\nclimbs from $0\\%$ at diffusion-only Cleveland Bay to $\\sim\\!27\\%$ at\nadvection-dominated Myrmidon, while the directly-forced storm source\nstays the largest single term (this is, after all, a *source*-recovery\nproblem). Cleveland Bay's storm response is mixing-and-forcing only;\nMyrmidon's carries a substantial upwelling signature; Davies Reef sits\nin between. Three moorings → three distinct storm-response fingerprints\nfrom one shared wind-stress event. **That contrast is what the joint\ninversion exploits and no single-site analysis can see.**\n\n### Step 6 — GPU full-scale run (measured)\n\nRunning [`task_b_joint_inverse.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_b_joint_inverse.jl){target=\"_blank\"}\non the course GPU hub (**NVIDIA A10G**) takes the recipe to all three\nsites at the wider $64\\times5$ network. These are\n*measured*, not extrapolated:\n\n| Run | Config | Wall-clock | $\\hat\\tau$ peak error |\n|---|---|---|---|\n| CPU 2-site prototype | 2 sites, $32\\times4$, 12k steps | ~7 min (joint) | 6.8% |\n| **GPU 3-site full-scale (A10G)** | 3 sites, $64\\times5$, 3k steps | **~5 min (joint), ~10 min (all four inversions)** | **6.7%** |\n\nThe per-site GPU breakdown tells the joint-inversion story directly:\nSite A alone recovers the peak to ~20%, Site B to ~15%, Site C to\n~12% — and the **shared-$\\tau$ joint of all three lands at 6.7%**,\nbetter than any single column. The advection-dominated Site C does\nbest alone (it carries the most storm information) yet still loses to\nthe joint.\n\nThe headline is that the GPU does the *harder* three-site /\nwider-network / deeper-column problem in **less** wall-clock than the\nCPU spent on the two-site prototype — that is what \"GPU buys you\nfull scale\" means here. (The raw training-step throughput behind that\nis benchmarked in [Unit 7 §7.6 ▸ *Why a GPU changes which PINNs you\ncan afford*](../unit_07/unit_07.qmd#sec-gpu): on the A10G the batched\ncollocation pass runs tens of times faster than the CPU.) A research\ngroup with three real moorings can re-run this on overnight GPU time.\n\n### Open questions for the full run\n\n- *Will causality violation re-appear at Myrmidon Reef\n  (advection-dominated, $\\mathrm{Pe} \\gg 1$)?* The two-site\n  prototype excluded Myrmidon precisely because its longer\n  characteristic timescale stresses the causal-training weights.\n  Possibly need a per-site causal scheduler.\n- *Will gradient-balancing converge on a stable weight ratio?*\n  Empirically yes on the sub-scale; theoretically not guaranteed.\n- *How well does the recovered $\\tau(t)$ correlate with the\n  independent SWE-driver $w(t)$ inferred from local wind\n  observations?* This is the validation step that turns the\n  recovered synthetic answer into something an oceanographer\n  trusts.\n\n### Files\n\n- [`scripts/task_b_subscale_prototype.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_b_subscale_prototype.jl){target=\"_blank\"} — two-site CPU sub-scale joint inverse (the headline prototype)\n- [`scripts/task_b_joint_inverse.jl`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_b_joint_inverse.jl){target=\"_blank\"} — three-site GPU full-scale joint trainer + mechanism partition\n- [`scripts/task_b_gpu_launch.md`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_b_gpu_launch.md){target=\"_blank\"} — GPU-launch checklist\n\n```{=html}\n  </div>\n</div>\n```\n\n## 10.4 A Python parallel with DeepXDE\n\n`DeepXDE` is the Python equivalent of `NeuralPDE.jl`: a high-level\ninterface that takes a PDE definition and a collocation strategy,\nproduces a trained network. Here's the Task A forward column\nproblem (Davies Reef, $H = 60$ m, fixed $\\tau$) as a DeepXDE\nsketch — same architecture (4 × 32 tanh MLP), same hard-BC\nansatz at the deep reservoir, same Adam → L-BFGS schedule. It conveys the\n*shape* of a DeepXDE port, not a byte-for-byte match to the Julia twin:\nthe forcing constants are round illustrative values and the diffusion is\nwritten non-conservatively ($\\kappa\\,\\partial_{zz}T$) for brevity:\n\n```{.python filename=\"units/unit_10/scripts/task_a_forward_deepxde.py\"}\n# pip install deepxde[torch]\nimport numpy as np\nimport deepxde as dde\n\nH = 60.0;  Tf = 30.0 * 86400.0\nT_deep = 22.0\ndef kappa_z(z):  return 1e-3 * np.exp(z / 20.0) + 1e-5    # mixed-layer profile (Site B)\ndef w_z(z, t):   return 5e-5 * (z + H) / H               # upwelling profile (Site B): linear in z (SWE), m/s\ndef Q_np(t):     return -120.0                           # net cooling (W/m^2)\ndef S_z(z, t):   return 400.0 / 4.0e6 / 8.0 * np.exp(z / 8.0)  # body source S = Q_SW/(ρ₀cₚζ)·e^(z/ζ), ζ=8 m\n\n# Geometry: z in [-H, 0], t in [0, Tf]\ngeom     = dde.geometry.Interval(-H, 0.0)\ntimedom  = dde.geometry.TimeDomain(0.0, Tf)\ngeomtime = dde.geometry.GeometryXTime(geom, timedom)\n\ndef pde(zt, T):\n    z, t = zt[:, 0:1], zt[:, 1:2]\n    dT_dt = dde.grad.jacobian(T, zt, j=1)\n    dT_dz = dde.grad.jacobian(T, zt, j=0)\n    d2T_dz2 = dde.grad.hessian(T, zt, component=0, i=0, j=0)\n    kappa = kappa_z(z)\n    return dT_dt + w_z(z, t) * dT_dz - kappa * d2T_dz2 - S_z(z, t)\n\n# Hard BC at the deep reservoir via output transform.\ndef output_transform(zt, T):\n    z = zt[:, 0:1]\n    return T_deep + (z + H) * T          # T(-H, t) = T_deep automatically\n\n# Soft surface flux at z = 0.\ndef surface_flux(zt, T, _):\n    dT_dz_top = dde.grad.jacobian(T, zt, j=0)\n    rho, cp = 1025.0, 3990.0\n    return rho * cp * kappa_z(zt[:, 0:1]) * dT_dz_top - Q_np(zt[:, 1:2])\nbc_surface = dde.icbc.OperatorBC(\n    geomtime, surface_flux,\n    lambda zt, on_boundary: on_boundary and np.isclose(zt[0], 0.0),\n)\n\n# IC: initial thermocline tanh profile (Site B: thermocline at z = -25 m)\ndef T0(z): return 25.0 + 3.0 * np.tanh((z + 25.0) / 5.0)\nic = dde.icbc.IC(geomtime, lambda zt: T0(zt[:, 0:1]),\n                 lambda _, on_initial: on_initial)\n\ndata = dde.data.TimePDE(\n    geomtime, pde, [bc_surface, ic],\n    num_domain=2000, num_boundary=200, num_initial=200,\n)\nnet = dde.nn.FNN([2] + [32] * 4 + [1], \"tanh\", \"Glorot uniform\")\nnet.apply_output_transform(output_transform)\nmodel = dde.Model(data, net)\nmodel.compile(\"adam\", lr=1e-3); model.train(iterations=2000)\nmodel.compile(\"L-BFGS\"); model.train()\n```\n\nAvailable as\n[`scripts/task_a_forward_deepxde.py`](https://github.com/open-AIMS/Julia_PINN_training_2026/blob/main/units/unit_10/scripts/task_a_forward_deepxde.py){target=\"_blank\"}.\nRuntime: ~5 min on a CPU with the PyTorch backend.\n\nThe structural one-to-one with the Julia version:\n\n| Concern | Julia (`NeuralPDE.jl`) | Python (`DeepXDE`) |\n|---|---|---|\n| Geometry | `IntervalDomain` × `TimeDomain` | `Interval` × `TimeDomain` |\n| Residual | `Differential(t)` + symbolic AD | `dde.grad.jacobian` / `hessian` |\n| Hard BC ansatz | manual product form | `apply_output_transform` |\n| Soft BC | `bcs` vector | `OperatorBC` |\n| Optimiser | `Optimization.solve(Adam → LBFGS)` | `model.compile/train` twice |\n| AD backend | Zygote + ForwardDiff | PyTorch / JAX / TF |\n\n### Cross-ecosystem comparison\n\nStrengths and weaknesses, honestly:\n\n- *Julia stack* — composes cleanly with classical SciML solvers,\n  faster autodiff for stiff problems, smaller ML community.\n- *Python stack* — broader ML community support, more ergonomic\n  when extending with bespoke loss terms, larger ecosystem of\n  pre-trained models and tutorials.\n\nNeither is strictly better. Pick by who's using it and what they\nalready know.\n\n## 10.5 Where to go from here {#sec-where-to-go}\n\nBeyond the workshop:\n\n- **Scenario 5 — couple in the shallow-water driver.** Replace the\n  prescribed scenario-4 envelopes with a physically self-consistent\n  $w(t)$ from the SWE solve sketched in §10.1, feeding each mooring's\n  horizontal divergence into its column. The linearised shallow-water\n  machinery in [Unit 1](../unit_01/unit_01.qmd) is the cleanest\n  starting point.\n- **Real mooring data** — replace the synthetic observations with\n  AIMS records.\n- **Coupling with operational ocean models** — ROMS, MOM6 — for\n  realistic horizontal forcings.\n- **Uncertainty quantification** on the recovered driver, via\n  Bayesian PINNs or ensembles.\n- **Transfer to other reef sites** with different climatologies.\n\nThe PINN software ecosystem you'd reach for next is catalogued in\n[Unit 7 §7.6](../unit_07/unit_07.qmd); the broader PIML field is\nmapped in [the references](../references/references.qmd).\n\n## 10.6 Reference solver source: `scripts/column_fd.jl`\n\nThe MethodOfLines finite-difference reference for $T(z, t)$, kept\nas a standalone script (see `SETUP.md`) so `quarto render` stays\ncheap. Run with `./build.sh execute 10`; outputs land in\n`output/`. Folded for brevity; expand to read.\n\n```{.julia code-fold=\"true\" code-summary=\"Show full source\"}\n# Reference 1D vertical heat-transport column solver (finite-difference,\n# method-of-lines). See unit_09.qmd for the model specification.\n#\n# Scenarios (per unit_09.qmd §9.11):\n#   1. pure diffusion to steady state\n#   2. diurnal cycle (Q_SW + body source S)\n#   3. add upwelling (w(z))\n#   4. storm fingerprint (gust modulates w, κ, Q_SW around day 10)\n#\n# Run a scenario:\n#   include(\"column_fd.jl\"); r = run_scenario(scenario_1());\n#   plot_scn1(r)\n\nusing ModelingToolkit, MethodOfLines, OrdinaryDiffEq\nusing OrdinaryDiffEqBDF: QNDF  # umbrella OrdinaryDiffEq no longer re-exports BDF solvers\nusing DomainSets: ClosedInterval\nusing CairoMakie\nusing Printf\n\n# ── reference parameters (unit_09.qmd §9.6) ────────────────────────────\nconst PARAMS = (\n    H         = 100.0,    # column depth (m)\n    ρ         = 1025.0,   # seawater density (kg/m³)\n    cp        = 3990.0,   # specific heat (J/(kg·K))\n    α         = 2e-4,     # thermal expansion (1/K)\n    T_surface = 28.0,     # initial SST (°C)\n    T_deep    = 18.0,     # deep reservoir (°C)\n    z_t       = -30.0,    # thermocline depth (m)\n    δ_t       = 5.0,      # thermocline sharpness (m)\n    QSW_max   = 800.0,    # peak noon shortwave (W/m²)\n    Q_cool    = 200.0,    # non-penetrative net cooling (W/m²)\n    ζ         = 10.0,     # shortwave penetration scale (m)\n    κ_b       = 1e-5,     # background diffusivity (m²/s)\n    κ_m       = 1e-3,     # mixed-layer diffusivity (m²/s)\n    h_m       = 20.0,     # mixed-layer scale (m)\n    w0        = 1e-5,     # peak upwelling (m/s)\n    τ_d       = 86400.0,  # diurnal period (s)\n    # storm scenario: Gaussian gust around day 10, ~3 days wide.\n    t_storm   = 10 * 86400.0,\n    σ_storm   = 1.0 * 86400.0,\n    w0_storm  = 5e-5,     # gust-driven upwelling (5× baseline)\n    cloud_amp = 0.5,      # peak SW reduction during gust\n)\n\nstorm_envelope(t, p) = exp(-((t - p.t_storm) / p.σ_storm)^2)\n\n# ── initial profile ─────────────────────────────────────────────────────\nT0(z, p=PARAMS) = 0.5*(p.T_surface + p.T_deep) +\n                  0.5*(p.T_surface - p.T_deep) * tanh((z - p.z_t)/p.δ_t)\n\n# ── vertical velocity profiles ──────────────────────────────────────────\nw_zero(z, t, p)       = 0.0\nw_upwelling(z, t, p)  = p.w0 * sin(π * (z + p.H) / p.H)\nw_storm(z, t, p)      = p.w0_storm * storm_envelope(t, p) * sin(π * (z + p.H) / p.H)\n\n# ── eddy diffusivity profiles ───────────────────────────────────────────\nκ_const(z, t, p)   = p.κ_m\nκ_profile(z, t, p) = p.κ_b + (p.κ_m - p.κ_b) * exp(z / p.h_m)\n\n# ── surface forcing ─────────────────────────────────────────────────────\n# Smooth diurnal: use (1 + cos)/2 instead of max(0, cos) to keep the RHS\n# differentiable for MTK. Same daily mean energy as max(0, cos)·(2/π)·QSW_max\n# would give, but a smooth half-cosine — close enough for the toy model.\nQSW_diurnal(t, p) = p.QSW_max * 0.5 * (1.0 + cos(2π * t / p.τ_d))\nQSW_storm(t, p)   = p.QSW_max * (1.0 - p.cloud_amp * storm_envelope(t, p)) *\n                    0.5 * (1.0 + cos(2π * t / p.τ_d))\nQ_np_steady(t, p) = -p.Q_cool\n\n# Body source from Beer–Lambert: I(z,t) = Q_SW(t) e^{z/ζ},\n# S = (1/(ρcp)) ∂I/∂z = Q_SW(t)/(ζ ρ cp) · e^{z/ζ}.\nS_off(z, t, p)     = 0.0\nS_diurnal(z, t, p) = QSW_diurnal(t, p) * exp(z / p.ζ) / (p.ζ * p.ρ * p.cp)\nS_storm(z, t, p)   = QSW_storm(t, p)   * exp(z / p.ζ) / (p.ζ * p.ρ * p.cp)\n\n# ── PDE builder ─────────────────────────────────────────────────────────\nfunction build_pde(scn, p=PARAMS)\n    @parameters z t\n    @variables T(..)\n    Dt = Differential(t)\n    Dz = Differential(z)\n\n    # Substitute scenario profiles symbolically so MOL sees closed-form\n    # expressions in (z, t).\n    w_sym  = scn.w(z, t, p)\n    κ_sym  = scn.κ(z, t, p)\n    S_sym  = scn.S(z, t, p)\n    Qnp_sym = scn.Q_np(t, p)\n    κ_top  = scn.κ(0.0, t, p)\n\n    eq = Dt(T(z, t)) + w_sym * Dz(T(z, t)) ~\n         Dz(κ_sym * Dz(T(z, t))) + S_sym\n\n    domains = [z ∈ ClosedInterval(-p.H, 0.0),\n               t ∈ ClosedInterval(0.0, scn.Tf)]\n\n    bcs = [\n        T(z, 0.0)   ~ T0(z, p),\n        T(-p.H, t)  ~ p.T_deep,\n        κ_top * Dz(T(0.0, t)) ~ Qnp_sym / (p.ρ * p.cp),\n    ]\n\n    @named pde_system = PDESystem(eq, bcs, domains, [z, t], [T(z, t)])\n    return pde_system, z, t, T\nend\n\n# ── run dispatcher ──────────────────────────────────────────────────────\nfunction run_scenario(scn; dz=1.0, p=PARAMS)\n    pde_system, z, t, T = build_pde(scn, p)\n    disc = MOLFiniteDifference([z => dz], t)\n    prob = discretize(pde_system, disc)\n    @info \"solving scenario: $(scn.name) (Tf = $(scn.Tf/86400) days)\"\n    sol = solve(prob, scn.alg; saveat=scn.saveat, abstol=1e-8, reltol=1e-6)\n    (; sol, z, t, T, scn)\nend\n\n# ── scenario configs ────────────────────────────────────────────────────\n# Tf chosen long enough to reach (near-)steady state: T_κ = H²/κ_m ≈ 116 days,\n# so ~3·T_κ ≈ 350 days gets us to within a few percent.\nscenario_1() = (\n    name   = \"diffusion to steady state\",\n    w      = w_zero,\n    κ      = κ_const,\n    S      = S_off,\n    Q_np   = Q_np_steady,\n    Tf     = 365 * 86400.0,\n    saveat = 10 * 86400.0,\n    alg    = QNDF(),\n)\n\nscenario_2() = (\n    name   = \"diurnal cycle\",\n    w      = w_zero,\n    κ      = κ_const,\n    S      = S_diurnal,\n    Q_np   = Q_np_steady,\n    Tf     = 10 * 86400.0,\n    saveat = 600.0,\n    alg    = QNDF(),\n)\n\nscenario_3() = (\n    name   = \"upwelling\",\n    w      = w_upwelling,\n    κ      = κ_const,\n    S      = S_diurnal,\n    Q_np   = Q_np_steady,\n    Tf     = 30 * 86400.0,\n    saveat = 3600.0,\n    alg    = QNDF(),\n)\n\n# Scenario 4 (storm): Gaussian gust centred at t_storm. The gust spikes\n# upwelling (w_storm) and dims the surface SW (cloud cover via S_storm).\n# Real SWE-driven forcings would replace these envelopes; this is the\n# prescribed-driver stub used in §9.11 task 5.\nscenario_4() = (\n    name   = \"storm fingerprint\",\n    w      = w_storm,\n    κ      = κ_const,\n    S      = S_storm,\n    Q_np   = Q_np_steady,\n    Tf     = 30 * 86400.0,\n    saveat = 3600.0,\n    alg    = QNDF(),\n)\n\n# ── analytic check for scenario 1 ───────────────────────────────────────\n# Steady state of (κ T_z)_z = 0 with T(-H)=T_deep and κ T_z|₀ = Q_np/(ρcp):\n#   T(z) = T_deep − (Q_cool/(κ_m ρ cp)) · (z + H)\n# (Using Q_np = -Q_cool < 0, so the surface is cooler than the deep\n# reservoir — heat flows up from depth to be lost at the air-sea\n# interface.)\nT_analytic_scn1(z, p=PARAMS) =\n    p.T_deep - p.Q_cool / (p.κ_m * p.ρ * p.cp) * (z + p.H)\n\n# ── plotting ────────────────────────────────────────────────────────────\n# Extract the (Nz, Nt) matrix and grids from a run_scenario result,\n# regardless of MOL's internal axis ordering. We declared PDESystem with\n# ivs = [z, t], so sol[z] and sol[t] are the canonical grids; we transpose\n# the matrix to (Nz, Nt) if MOL returned it in (Nt, Nz) form.\nfunction _grids(r)\n    zg = r.sol[r.z]\n    tg = r.sol[r.t]\n    Tg = r.sol[r.T(r.z, r.t)]\n    Tg = size(Tg, 1) == length(zg) ? Tg : permutedims(Tg)\n    (zg, tg, Tg)\nend\n\n\"Final-time T(z) vs analytic steady state.\"\nfunction plot_scn1(r; outpath=joinpath(@__DIR__, \"..\", \"output\", \"scn1_steady.png\"))\n    zg, tg, Tg = _grids(r)\n    Tf = Tg[:, end]\n    fig = Figure(size=(700, 500))\n    ax = Axis(fig[1,1], xlabel=\"T (°C)\", ylabel=\"z (m)\",\n              title=\"Scenario 1: pure diffusion to (near-)steady state\")\n    # Draw the MOL solution first (solid), then the analytic steady state\n    # as a dashed overlay ON TOP, in a contrasting colour — otherwise the\n    # solid MOL line hides the dashes entirely (the two agree to ~4e-3 °C,\n    # so the visible dashes riding on the orange line ARE the validation).\n    lines!(ax, Tf, zg; linewidth=3, label=\"MOL final\")\n    lines!(ax, T_analytic_scn1.(zg), zg;\n           linestyle=:dash, linewidth=2, color=:black, label=\"analytic\")\n    lines!(ax, T0.(zg), zg;\n           color=:gray, linewidth=1, label=\"IC\")\n    axislegend(ax, position=:rb)\n    save(outpath, fig)\n    err = maximum(abs, Tf .- T_analytic_scn1.(zg))\n    @info \"saved $outpath; max |T_MOL − T_analytic| = $(round(err, sigdigits=3)) °C\"\n    fig\nend\n\n\"Scenario 2: near-surface traces (showing the diurnal cycle) over the (z, t) heatmap.\"\nfunction plot_scn2(r; zmax=10.0,\n                   outpath=joinpath(@__DIR__, \"..\", \"output\", \"scn2_diurnal.png\"))\n    zg, tg, Tg = _grids(r)\n    days = tg ./ 86400.0\n    keep = zg .>= -zmax\n    fig = Figure(size=(900, 640))\n\n    # Top: a few near-surface traces — the daily warm/cool cycle is obvious here\n    # even though it is washed out by the slow relaxation in the heatmap below.\n    ax1 = Axis(fig[1,1], xlabel=\"t (days)\", ylabel=\"T (°C)\",\n               title=\"Scenario 2: diurnal warm layer — near-surface traces\")\n    for (d, col) in ((1.0, :firebrick), (3.0, :darkorange), (7.0, :seagreen))\n        zi = argmin(abs.(zg .+ d))\n        lines!(ax1, days, Tg[zi, :]; color=col, linewidth=1.6, label=\"z = −$(Int(d)) m\")\n    end\n    axislegend(ax1, position=:rt, framevisible=true)\n\n    ax2 = Axis(fig[2,1], xlabel=\"t (days)\", ylabel=\"z (m)\", title=\"T(z, t) — top $(Int(zmax)) m\")\n    hm = heatmap!(ax2, days, zg[keep], Tg[keep, :]')\n    Colorbar(fig[2,2], hm, label=\"T (°C)\")\n    rowsize!(fig.layout, 1, Relative(0.42))\n    save(outpath, fig)\n    @info \"saved $outpath\"\n    fig\nend\n\n\"Five-mooring-depth time series + full (z,t) heatmap for scenarios 3–4.\"\nfunction plot_mooring(r; depths_m=(2.0, 10.0, 30.0, 60.0, 90.0),\n                      outpath=joinpath(@__DIR__, \"..\", \"output\", \"$(replace(r.scn.name, ' '=>'_'))_mooring.png\"))\n    zg, tg, Tg = _grids(r)\n    days = tg ./ 86400.0\n    fig = Figure(size=(1000, 700))\n    ax1 = Axis(fig[1,1], xlabel=\"t (days)\", ylabel=\"T (°C)\",\n               title=\"Mooring traces — $(r.scn.name)\")\n    for d in depths_m\n        zi = argmin(abs.(zg .+ d))  # z = -d\n        lines!(ax1, days, Tg[zi, :]; label=\"z = −$(d) m\")\n    end\n    axislegend(ax1, position=:rt)\n    ax2 = Axis(fig[2,1], xlabel=\"t (days)\", ylabel=\"z (m)\",\n               title=\"T(z, t)\")\n    hm = heatmap!(ax2, days, zg, Tg')\n    Colorbar(fig[2,2], hm, label=\"T (°C)\")\n    save(outpath, fig)\n    @info \"saved $outpath\"\n    fig\nend\n\n# ── entry point when run as script ──────────────────────────────────────\n# Used by ./build.sh execute 10 to populate units/unit_10/output/.\nif abspath(PROGRAM_FILE) == @__FILE__\n    r1 = run_scenario(scenario_1());  plot_scn1(r1)\n    r2 = run_scenario(scenario_2());  plot_scn2(r2)\n    r3 = run_scenario(scenario_3());  plot_mooring(r3)\n    r4 = run_scenario(scenario_4());  plot_mooring(r4)\nend\n\n```\n\nRunning it produces:\n\n::: {.cell-output .cell-output-stdout}\n```text\n[ Info: solving scenario: diffusion to steady state (Tf = 365.0 days)\n[ Info: saved units/unit_10/output/scn1_steady.png; max |T_MOL − T_analytic| = 0.00407 °C\n[ Info: solving scenario: diurnal cycle (Tf = 10.0 days)\n[ Info: saved units/unit_10/output/scn2_diurnal.png\n[ Info: solving scenario: upwelling (Tf = 30.0 days)\n[ Info: saved units/unit_10/output/upwelling_mooring.png\n[ Info: solving scenario: storm fingerprint (Tf = 30.0 days)\n[ Info: saved units/unit_10/output/storm_fingerprint_mooring.png\n```\n:::\n\n",
    "supporting": [
      "unit_10_files"
    ],
    "filters": [],
    "includes": {}
  }
}